const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const report={};for(const name of ['spin-jump','spin-shield','burrow','burrow-turn','air-dive','air-recovery']){
 const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://127.0.0.1:4199/remix-check.html?battle=72,74,16,0&SSB64_REMIX_TEST=1');await p.waitForFunction(()=>window.driver,{},{timeout:60000});
 const r=await p.evaluate(name=>{let rows=[];const tick=(n,a=[0,0,0],b=[0,0,0])=>{pads=[a,b];for(let j=0;j<n;j++){driver.step();rows.push(probe())}};for(let n=0;(window.state?.[4]||0)<30&&n<900;n++)tick(1);if(!game.contentWindow.Module._port_remix_test_place(name==='spin-shield'?300:800))throw Error('place');tick(2);rows=[];
 if(name==='spin-jump'){tick(1,[16384,0,0]);tick(3);tick(1,[8,70,0]);tick(150);}
 if(name==='spin-shield'){tick(10,[0,0,0],[8192,0,0]);tick(1,[16384,0,0],[8192,0,0]);tick(100,[0,0,0],[8192,0,0]);}
 if(name==='burrow'||name==='burrow-turn'){tick(60,[16384,0,-70]);if(name==='burrow-turn'){tick(16,[16384,-70,0]);tick(20,[16384,70,0]);}else tick(14,[16384,70,0]);tick(200);}
 if(name==='air-dive'||name==='air-recovery'){tick(1,[8,0,0]);tick(22);tick(1,[16384,0,name==='air-dive'?-70:70]);tick(200);}
 return rows;},name);await fs.writeFile(`build/remix/main/checks/crash-${name}.json`,JSON.stringify(r));report[name]={statuses:[...new Set(r.map(x=>x[1]))],xmax:Math.max(...r.map(x=>x[3])),ymax:Math.max(...r.map(x=>x[4])),last:r.at(-1)[1],damage:r.at(-1)[18],errors};console.log(name,report[name]);assert.deepEqual(errors,[]);if(name==='burrow'){await p.screenshot({path:'build/remix/main/checks/crash-burrow.png'});}await p.close();}
 await fs.writeFile('build/remix/main/checks/crash-edges.json',JSON.stringify(report,null,2));assert(report['spin-jump'].statuses.includes(224));assert(report['spin-shield'].statuses.includes(225));assert(report.burrow.statuses.includes(228)&&report.burrow.statuses.includes(230));assert(report['burrow-turn'].statuses.includes(229));assert(report['air-dive'].statuses.includes(232)&&report['air-dive'].statuses.includes(227));assert(report['air-recovery'].statuses.includes(234));
}finally{await browser.close()}})();
