const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const report={};for(const name of ['inhale-spit','inhale-turn','inhale-projectile','jump-cancel','minion-dee','minion-doo','minion-gordo']){
 const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://127.0.0.1:4199/remix-check.html?battle=64,0,16,0&SSB64_REMIX_TEST=1');await p.waitForFunction(()=>window.driver,{},{timeout:60000});
 const r=await p.evaluate(name=>{let rows=[],items=[];const tick=(n,a=[0,0,0],b=[0,0,0])=>{pads=[a,b];for(let j=0;j<n;j++){driver.step();rows.push(probe());let w=game.contentWindow,q=w.Module._port_remix_entity_probe()>>2,v=Array.from(w.HEAP32.slice(q,q+322));items.push(Array.from({length:v[0]+v[1]},(_,i)=>v.slice(2+i*10,12+i*10)))}};for(let n=0;(window.state?.[4]||0)<30&&n<900;n++)tick(1);if(!game.contentWindow.Module._port_remix_test_place(name==='inhale-projectile'?1800:name.startsWith('inhale-')?260:800))throw Error('place');tick(2);rows=[];items=[];
 if(name==='inhale-spit'){tick(80,[16384,0,0]);tick(1);tick(1,[16384,0,0]);tick(130);}
 if(name==='inhale-turn'){tick(80,[16384,0,0]);tick(25,[0,-70,0]);tick(1,[32768,0,0]);tick(130);}
 if(name==='inhale-projectile'){tick(35,[16384,0,0]);tick(1,[16384,0,0],[16384,0,0]);tick(140,[16384,0,0]);tick(80);}
 if(name==='jump-cancel'){tick(1,[16384,0,70]);tick(65);tick(1,[16384,0,0]);tick(110);}
 if(name.startsWith('minion-')){tick(name==='minion-dee'?30:name==='minion-doo'?80:140,[16384,0,-70]);tick(2);if(name==='minion-gordo'){tick(1,[16384,0,-70]);}tick(350);}
 return {rows,items};},name);await fs.writeFile(`build/remix/main/checks/dedede-${name}.json`,JSON.stringify(r));report[name]={statuses:[...new Set(r.rows.map(x=>x[1]))],foeStatuses:[...new Set(r.rows.map(x=>x[17]))],xmax:Math.max(...r.rows.map(x=>x[3])),ymax:Math.max(...r.rows.map(x=>x[4])),last:r.rows.at(-1)[1],damage:r.rows.at(-1)[18],entities:Math.max(...r.items.map(x=>x.length)),errors};console.log(name,report[name]);assert.deepEqual(errors,[]);await p.close();}
 await fs.writeFile('build/remix/main/checks/dedede-edges.json',JSON.stringify(report,null,2));assert(report['inhale-spit'].damage>=16);assert(report['inhale-projectile'].statuses.includes(237)&&report['inhale-projectile'].damage>0);assert(report['minion-dee'].entities>0);assert(report['minion-doo'].entities>0);assert(report['minion-gordo'].entities>0);
}finally{await browser.close()}})();
