const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const report={};for(const name of ['charged-coin','walk-charge','cloud-jump','cloud-attack','cloud-escape','chain','air-chain']){
 const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://127.0.0.1:4199/remix-check.html?battle=65,74,16,0&SSB64_REMIX_TEST=1');await p.waitForFunction(()=>window.driver,{},{timeout:60000});
 const r=await p.evaluate(name=>{let rows=[],items=[];const tick=(n,a=[0,0,0],b=[0,0,0])=>{pads=[a,b];for(let j=0;j<n;j++){driver.step();rows.push(probe());let w=game.contentWindow,q=w.Module._port_remix_entity_probe()>>2,v=Array.from(w.HEAP32.slice(q,q+322));items.push(Array.from({length:v[0]+v[1]},(_,i)=>v.slice(2+i*10,12+i*10)))}};for(let n=0;(window.state?.[4]||0)<30&&n<900;n++)tick(1);if(!game.contentWindow.Module._port_remix_test_place(name.includes('chain')?600:800))throw Error('place');tick(2);rows=[];items=[];
 if(name==='charged-coin'){tick(70,[16384,0,0]);tick(120);}
 if(name==='walk-charge'){tick(30,[16384,0,0]);tick(15,[16384,-70,0]);tick(15,[16384,70,0]);tick(140);}
 if(name.startsWith('cloud-')){tick(1,[16384,0,70]);tick(20,[0,20,70]);tick(1,[name==='cloud-jump'?8:name==='cloud-attack'?32768:8192,0,0]);tick(180);}
 if(name==='chain'){tick(1,[16384,0,-70]);tick(160);}
 if(name==='air-chain'){tick(1,[8,0,0]);tick(2);tick(1,[16384,0,-70]);tick(160);}
 return {rows,items};},name);await fs.writeFile(`build/remix/main/checks/goemon-${name}.json`,JSON.stringify(r));report[name]={statuses:[...new Set(r.rows.map(x=>x[1]))],foeStatuses:[...new Set(r.rows.map(x=>x[17]))],xmax:Math.max(...r.rows.map(x=>x[3])),ymax:Math.max(...r.rows.map(x=>x[4])),last:r.rows.at(-1)[1],damage:r.rows.at(-1)[18],entities:Math.max(...r.items.map(x=>x.length)),errors};console.log(name,report[name]);assert.deepEqual(errors,[]);await p.close();}
 await fs.writeFile('build/remix/main/checks/goemon-edges.json',JSON.stringify(report,null,2));assert(report['charged-coin'].damage>11);assert(report['walk-charge'].statuses.includes(232));assert(report['cloud-jump'].statuses.includes(225)&&report['cloud-jump'].entities>0);assert(report['cloud-attack'].statuses.includes(224));assert(report['cloud-escape'].statuses.includes(226));assert(report.chain.statuses.includes(238)&&report.chain.statuses.includes(245));
}finally{await browser.close()}})();
