const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const report={};for(const [name,id,victim] of [['cargo',63,74],['cargo-jump',63,58],['wario-grab',33,74],['kirby-swallow',8,58],['kirby-spit',8,64],['captain-grab',7,64]]){
 const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(`http://127.0.0.1:4199/remix-check.html?battle=${id},${victim},16,0&SSB64_REMIX_TEST=1`);await p.waitForFunction(()=>window.driver,{},{timeout:60000});
 const r=await p.evaluate(name=>{let rows=[],maxEntities=0;const tick=(n,a=[0,0,0],b=[0,0,0])=>{pads=[a,b];for(let i=0;i<n;i++){driver.step();rows.push(probe());let w=game.contentWindow,q=w.Module._port_remix_entity_probe()>>2;maxEntities=Math.max(maxEntities,w.HEAP32[q]+w.HEAP32[q+1]);}};for(let n=0;(window.state?.[4]||0)<30&&n<900;n++)tick(1);if(!game.contentWindow.Module._port_remix_test_place(260))throw Error('place');tick(2);rows=[];
 if(name.startsWith('kirby')){tick(80,[16384,0,0]);tick(2);tick(1,name==='kirby-swallow'?[0,0,-70]:[32768,0,0]);tick(180);}
 else if(name==='captain-grab'){tick(1,[16384,0,70]);tick(180);}
 else{tick(1,[40960,0,0]);tick(45);tick(1,[32768,0,0]);tick(65);if(name==='cargo'){for(let n=0;n<160;n++)tick(1,[n%7===0?16384:0,0,0]);tick(30);tick(1,[32768,0,0]);tick(180);}else if(name==='cargo-jump'){tick(1,[8,0,0]);tick(24);tick(1,[32768,0,0]);tick(180);}else tick(150);}
 return {rows,maxEntities};},name);report[name]={statuses:[...new Set(r.rows.map(x=>x[1]))],victimStatuses:[...new Set(r.rows.map(x=>x[17]))],damage:r.rows.at(-1)[18],last:r.rows.at(-1)[1],maxEntities:r.maxEntities,errors};console.log(name,report[name]);await fs.writeFile(`build/remix/main/checks/grab-${name}.json`,JSON.stringify(r));assert.deepEqual(errors,[]);await p.close();}
 await fs.writeFile('build/remix/main/checks/grabs.json',JSON.stringify(report,null,2));assert(report.cargo.statuses.includes(235));assert(report.cargo.statuses.includes(251));assert(report.cargo.maxEntities>0);assert(report['cargo-jump'].statuses.includes(250));assert(report['wario-grab'].victimStatuses.includes(184));assert(report['kirby-swallow'].damage>0);assert(report['kirby-spit'].damage>0);
}finally{await browser.close()}})();
