const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const p=await b.newPage({viewport:{width:960,height:720}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://127.0.0.1:4199/presentation-check.html');await p.waitForFunction(()=>window.driver,{},{timeout:60000});
const setup=await p.evaluate(()=>{const step=(n,port=0,pad=[0,0,0])=>{pads=Array.from({length:4},()=>[0,0,0]);pads[port]=pad;for(let i=0;i<n;i++)driver.step();};const menu=()=>({...game.contentWindow.Module.remixMenu});
// Only the first human's hand is reported, so steer each port by dead reckoning from its card home (44+69*port,168): 1 px per 20 stick units a frame, puck centre 13 px right of and 1 px above the hand.
const cell=i=>i<30?[39+(i%10)*24,44+Math.floor(i/10)*24]:[111+(i-30)*24,120];const stick=v=>{let s=Math.max(-80,Math.min(80,Math.round(v*20)));if(s&&Math.abs(s)<=8)s=Math.sign(s)*9;return s;};
const place=(port,i)=>{const [cx,cy]=cell(i),tx=cx-1,ty=cy+13;let x=44+69*port,y=168;for(let n=0;n<400&&(Math.abs(tx-x)>=1||Math.abs(ty-y)>=1);n++){const sx=stick(tx-x),sy=stick(y-ty);step(1,port,[0,sx,sy]);if(Math.abs(sx)>8)x+=Math.fround(sx/20);if(Math.abs(sy)>8)y-=Math.fround(sy/20);}step(1,port,[32768,0,0]);step(20);};
step(40);place(0,0);let joins=[];for(let port=1;port<4;port++){step(1,port,[4096,0,0]);step(20);joins.push(menu());place(port,port);}const before=menu();step(1,0,[4096,0,0]);step(1);const ready=menu();step(60);return {joins,before,ready,stages:menu()};});console.log(setup);assert.equal(setup.before.humans,15);assert.equal(setup.before.active,15);assert.equal(setup.before.confirmed,15);assert.equal(setup.before.held,0);assert.equal(setup.before.phase,0);assert.equal(setup.ready.phase,3);assert.equal(setup.stages.phase,2);await p.screenshot({path:'build/remix/main/checks/local-four-select.png'});
const match=await p.evaluate(()=>{const step=(n,port=0,pad=[0,0,0])=>{pads=Array.from({length:4},()=>[0,0,0]);pads[port]=pad;for(let i=0;i<n;i++)driver.step();};step(1,0,[32768,0,0]);step(800);const probe=()=>{const w=game.contentWindow,q=w.Module._port_remix_multiplayer_probe()>>2;return Array.from(w.HEAP32.slice(q,q+26));};const before=probe(),moves=[];for(let port=0;port<4;port++){step(1,port,[8,0,0]);step(8,port,[0,port&1?-60:60,0]);moves.push(probe());step(65);}return {before,moves};});console.log(match);assert.equal(match.before[0],4);assert.equal(match.before[1],0);for(let i=0;i<4;i++){assert.equal(match.before[5+i*6],10);assert([21,22,23,24,25,26,27,28,29,30,31].includes(match.moves[i][5+i*6]),`P${i+1} did not jump`);}assert.deepEqual(errors,[]);await p.screenshot({path:'build/remix/main/checks/local-four-battle.png'});const finish=await p.evaluate(()=>{const w=game.contentWindow,m=w.Module;let frames=0;pads=Array.from({length:4},()=>[0,0,0]);while(!m.remixResults&&frames<6000){if(frames%240===0)for(let port=0;port<3;port++)m._port_remix_test_position(port,4900,100);driver.step();frames++;}if(!m.remixResults)throw Error('Four-player match did not finish');const result={...m.remixResults,frames};for(let n=0;n<80;n++)driver.step();return result;});assert.equal(finish.winner,3);assert.equal(finish.fighters.length,4);await p.screenshot({path:'build/remix/main/checks/local-four-results.png'});const returned=await p.evaluate(()=>{pads=[[32768,0,0]];driver.step();pads=[[0,0,0]];for(let n=0;n<100;n++)driver.step();return {...game.contentWindow.Module.remixMenu};});assert.equal(returned.phase,0);assert.equal(returned.humans,15);assert.equal(returned.active,15);assert.equal(returned.p1,setup.ready.p1);assert.equal(returned.p2,setup.ready.p2);assert.equal(returned.confirmed,15);assert.deepEqual(errors,[]);console.log({finish,returned});await fs.writeFile('build/remix/main/checks/local-four.json',JSON.stringify({setup,match,finish,returned,errors},null,2));
}finally{await b.close()}})();
