const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const report={};for(const level of [1,2,3,4]){
 const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://127.0.0.1:4199/remix-check.html?battle=63,0,16,0&SSB64_REMIX_TEST=1');await p.waitForFunction(()=>window.driver,{},{timeout:60000});
 const r=await p.evaluate(async level=>{const {NativeCheckpoints}=await import("/checkpoints.mjs");let rows=[],items=[],inputs=[];const tick=(n,a=[0,0,0],b=[0,0,0])=>{pads=[a,b];for(let j=0;j<n;j++){inputs.push([a,b]);driver.step();rows.push(probe());let w=game.contentWindow,q=w.Module._port_remix_entity_probe()>>2,v=Array.from(w.HEAP32.slice(q,q+322));items.push(Array.from({length:v[0]+v[1]},(_,i)=>v.slice(2+i*10,12+i*10)))}};
 for(let n=0;(window.state?.[4]||0)<30&&n<900;n++)tick(1);if(!game.contentWindow.Module._port_remix_test_place(800))throw Error('place');tick(2);rows=[];items=[];inputs=[];const store=new NativeCheckpoints(driver,{window:800}),snap=store.save(0,state);
 tick(50,[16384,0,-70]);for(let i=0;i<level;i++){tick(1,[16384,0,0],[16384,0,0]);tick(55,[16384,0,0]);}
 const absorbedEnd=rows.length;tick(1);tick(1,[16384,0,0]);tick(65);const pullEnd=rows.length;
 tick(1,[32768,70,0]);tick(140);const original={rows,items,absorbedEnd,pullEnd};let replay=inputs;state=store.load(snap);rows=[];items=[];inputs=[];for(const [a,b] of replay)tick(1,a,b);if(JSON.stringify({rows,items})!==JSON.stringify({rows:original.rows,items:original.items}))throw Error("Marina item rollback diverged");return {...original,rollback:true};},level);
 await fs.writeFile(`build/remix/main/checks/marina-clan${level}.json`,JSON.stringify(r));report[level]={statuses:[...new Set(r.rows.map(x=>x[1]))],damage:r.rows[r.absorbedEnd-1][2],foeDamage:r.rows.at(-1)[18],items:[...new Set(r.items.flat().map(x=>JSON.stringify([x[0],x[1],x[7],x[8],x[9]])))],rollback:r.rollback,errors};console.log(level,report[level]);assert.deepEqual(errors,[]);await p.close();}
 await fs.writeFile('build/remix/main/checks/marina-edges.json',JSON.stringify(report,null,2));for(const r of Object.values(report)){assert(r.statuses.includes(256),'absorb');assert(r.statuses.includes(258),'pull');assert(r.items.some(x=>JSON.parse(x)[3]===1),'held');assert.equal(r.damage,0,'absorbed fireballs');assert(r.foeDamage>0,"item hit");assert(r.rollback);}
}finally{await browser.close()}})();
