const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const p=await b.newPage({viewport:{width:960,height:720}}),voices=[],errors=[],logs=[];p.on('console',m=>{logs.push(m.text());if(logs.length>30)logs.shift();if(m.text().includes('VOICE:'))voices.push(m.text())});p.on('pageerror',e=>errors.push(String(e)));
await p.goto('http://127.0.0.1:4199/presentation-check.html');await p.waitForFunction(()=>window.driver,{},{timeout:60000});await p.frames().find(f=>f.url().includes('/engine/')).locator('canvas').click();
const selections=await p.evaluate(()=>{const M=()=>game.contentWindow.Module.remixMenu;const tick=(n,pad=[0,0,0])=>{pads=[pad];for(let i=0;i<n;i++)driver.step();};
// The native hand: the stick moves it 1 px per 20 units a frame, the held puck's centre rides 13 px right of and 1 px above the hand's origin, A drops it on the portrait beneath and lifts it again.
const cell=i=>i<30?[39+(i%10)*24,44+Math.floor(i/10)*24]:[111+(i-30)*24,120];const stick=v=>{let s=Math.max(-80,Math.min(80,Math.round(v*20)));if(s&&Math.abs(s)<=8)s=Math.sign(s)*9;return s;};
const moveTo=i=>{const [cx,cy]=cell(i),tx=cx-1,ty=cy+13;for(let n=0;n<400;n++){const m=M(),dx=tx-m.x,dy=ty-m.y;if(Math.abs(dx)<1&&Math.abs(dy)<1)return;tick(1,[0,stick(dx),stick(-dy)]);}throw Error('hand never reached portrait '+i);};
tick(40);const seen=[];for(let i=0;i<34;i++){moveTo(i);if(M().cursor!==i)throw Error(`puck over ${M().cursor}, not ${i}`);window.progress={i,menu:{...M()}};tick(1,[32768,0,0]);tick(35);if(M().held&1)throw Error('puck not placed at '+i);seen.push(M().hover);tick(1,[32768,0,0]);tick(5);if(!(M().held&1))throw Error('puck not lifted at '+i);}return seen;}).catch(async e=>{console.log(await p.evaluate(()=>({progress:window.progress,events})));console.log(voices);console.log(logs);throw e;});
assert.equal(new Set(selections).size,34);assert.equal(voices.filter(x=>x.includes('VOICE: play')).length,22);assert.deepEqual(errors,[]);
const result=await p.evaluate(()=>{const m=game.contentWindow.Module;if(!m._port_remix_online_results(29,58,1,0,2))throw Error('Result export rejected');pads=[[0,0,0]];for(let i=0;i<100;i++)driver.step();return m.remixResults;});await p.screenshot({path:'build/remix/main/checks/online-victory.png'});assert.equal(result.winner,1);assert.equal(result.animated,true);
const events=await p.evaluate(()=>{pads=[[32768,0,0]];driver.step();pads=[[0,0,0]];for(let i=0;i<35;i++)driver.step();pads=[[16384,0,0]];driver.step();return window.events;});assert.deepEqual(events,[[3,0],[2,0]]);
await fs.writeFile('build/remix/main/checks/presentation.json',JSON.stringify({selections,voices,result,events,errors},null,2));console.log({selected:selections.length,voices:22,result,events,errors});
}finally{await b.close()}})();
