extern WPDesc dITStarRodWeaponStarWeaponDesc;
/* WaddleDee.asm, WaddleDoo.asm and Gordo.asm. Every minion owns its state. */
typedef struct {int type,mode,timer,refresh,trade;float terminal;GObj *creator,*beam;} DededeMinion;
#define MINION(ip) ((DededeMinion*)&(ip)->item_vars)
_Static_assert(sizeof(DededeMinion)<=sizeof(((ITStruct*)0)->item_vars),"Minion state fits");
static sb32 minion_update(GObj*);
static int minion_is(GObj *g){return sonic_live(g,nGCCommonLinkIDItem)&&itGetStruct(g)->proc_update==minion_update;}
static void minion_texture(GObj *g,int image){MObj *m=DObjGetStruct(g)->mobj;if(m)m->texture_id_curr=image;}
static void minion_mode(GObj *g,int mode){ITStruct *ip=itGetStruct(g);DededeMinion *s=MINION(ip);s->mode=mode;s->timer=0;ip->attack_coll.attack_state=mode==1? nGMAttackStateNew:nGMAttackStateOff;if(mode>=2){ip->physics.vel_air.y=0;DObjGetStruct(g)->rotate.vec.f.z=0;}if(mode==1){itMapSetAir(ip);minion_texture(g,0);}else if(mode==2){itMapSetGround(ip);minion_texture(g,1);func_800269C0_275C0(0x44B);}else if(mode==3){itMapSetGround(ip);ip->physics.vel_air.x=ip->lr*15;ip->damage_coll.hitstatus=nGMHitStatusNormal;}else if(mode==4){ip->physics.vel_air.x=0;minion_texture(g,5);if(s->type==1)func_800269C0_275C0(0xDC);}}
static sb32 minion_dead(GObj *g){ITStruct *ip=itGetStruct(g);DededeMinion *s=MINION(ip);if(sonic_live(s->creator,nGCCommonLinkIDFighter)){FTStruct *fp=ftGetStruct(s->creator);if(fp->fkind==64&&DEDEDE(fp)->minion==g)DEDEDE(fp)->minion=NULL;}return TRUE;}
static sb32 minion_expire(GObj *g){efManagerDustExpandSmallMakeEffect(&DObjGetStruct(g)->translate.vec.f,1);return minion_dead(g);}
static GObj *minion_target(GObj *g){ITStruct *ip=itGetStruct(g);DededeMinion *s=MINION(ip);Vec3f p=DObjGetStruct(g)->translate.vec.f;GObj *best=NULL;float nearest=1e10F;for(GObj *f=gGCCommonLinks[nGCCommonLinkIDFighter];f;f=f->link_next){FTStruct *fp=ftGetStruct(f);if(f==ip->owner_gobj||fp->status_id<10||fp->is_ghost||(gSCManagerBattleState->is_team_battle&&fp->team==ip->team))continue;Vec3f q=DObjGetStruct(f)->translate.vec.f;float x=(q.x-p.x)*ip->lr,y=q.y-p.y;if(x>=0&&x<=(s->type==1?1096:600)&&ABSF(y)<=(s->type==1?600:700)&&x<nearest){best=f;nearest=x;}}return best;}
typedef struct {GObj *parent;int startup,time;float angle;} DooBeam;
#define DOOBEAM(wp) ((DooBeam*)&(wp)->weapon_vars)
static sb32 doo_beam_update(GObj *g){WPStruct *wp=wpGetStruct(g);DooBeam *s=DOOBEAM(wp);if(s->startup){--s->startup;return FALSE;}if(++s->time>=10)return TRUE;int show=(s->time&2)!=0;DObjGetStruct(g)->flags=show?0:DOBJ_FLAG_HIDDEN;wp->attack_coll.attack_state=show?nGMAttackStateNew:nGMAttackStateOff;if(!(s->time&1)){s->angle-=0.26171875F;int parent_item=minion_is(s->parent),parent_star=sonic_live(s->parent,nGCCommonLinkIDWeapon)&&wpGetStruct(s->parent)->proc_update==doo_beam_update;if(parent_item||parent_star){Vec3f p=DObjGetStruct(s->parent)->translate.vec.f;DObjGetStruct(g)->translate.vec.f=(Vec3f){p.x+256*wp->lr,p.y+256*sinf(s->angle),0};}memset(wp->attack_coll.attack_records,0,sizeof(wp->attack_coll.attack_records));}return FALSE;}
static GObj *doo_beam(GObj *g,GObj *parent){ITStruct *ip=itGetStruct(g);Vec3f p=DObjGetStruct(parent)->translate.vec.f;WPDesc d=dITStarRodWeaponStarWeaponDesc;d.proc_update=doo_beam_update;d.proc_map=d.proc_hit=d.proc_shield=d.proc_hop=d.proc_setoff=d.proc_reflector=d.proc_absorb=NULL;GObj *w=wpManagerMakeWeapon(g,&d,&p,WEAPON_FLAG_PARENT_ITEM);if(!w)return NULL;WPStruct *wp=wpGetStruct(w);memset(&wp->weapon_vars,0,sizeof(wp->weapon_vars));DOOBEAM(wp)->parent=parent;DOOBEAM(wp)->angle=1.125F;DOOBEAM(wp)->startup=10;wp->physics.vel_air=(Vec3f){0,0,0};wp->attack_coll.attack_state=nGMAttackStateOff;wp->attack_coll.damage=2;wp->attack_coll.element=3;wp->attack_coll.can_setoff=FALSE;wp->lr=ip->lr;DObjGetStruct(w)->flags=DOBJ_FLAG_HIDDEN;DObjGetStruct(w)->translate.vec.f=(Vec3f){p.x+256*ip->lr,p.y+256*sinf(1.125F),0};return w;}
static sb32 minion_update(GObj *g){ITStruct *ip=itGetStruct(g);DededeMinion *s=MINION(ip);if(s->mode==0){GObj *f=s->creator;if(!sonic_live(f,nGCCommonLinkIDFighter)||ftGetStruct(f)->fkind!=64||DEDEDE(ftGetStruct(f))->minion!=g||ftGetStruct(f)->status_id<248||ftGetStruct(f)->status_id>253)return minion_dead(g);Vec3f p={144,0,0};gmCollisionGetFighterPartsWorldPosition(ftGetStruct(f)->joints[10],&p);DObjGetStruct(g)->translate.vec.f=p;minion_texture(g,((++s->timer)/4)&1);return FALSE;}if(--ip->lifetime<=0)return minion_expire(g);if(s->refresh&&!--s->refresh)memset(ip->attack_coll.attack_records,0,sizeof(ip->attack_coll.attack_records));s->trade=0;s->timer++;
 if(s->mode==1){s->terminal=MAX(48,s->terminal-1);itMainApplyGravityClampTVel(ip,2,s->terminal);float speed=sqrtf(SQUARE(ip->physics.vel_air.x)+SQUARE(ip->physics.vel_air.y));if(ip->physics.vel_air.x)ip->lr=ip->physics.vel_air.x<0?-1:1;DObjGetStruct(g)->rotate.vec.f.z-=(0.017578125F+speed*(s->type==2?0.001F:0.003F))*ip->lr;if(s->type==2&&speed>=35&&!s->refresh)memset(ip->attack_coll.attack_records,0,sizeof(ip->attack_coll.attack_records));}
 else if(s->mode==2){ip->physics.vel_air.x*=0.9375F;if(ABSF(ip->physics.vel_air.x)<2){ip->physics.vel_air.x=0;ip->attack_coll.attack_state=nGMAttackStateOff;}if(s->timer>=16)minion_mode(g,3);}
 else if(s->mode==3){minion_texture(g,2+(s->timer/4)%3);if(!(s->timer&15)&&minion_target(g))minion_mode(g,4);}
 else if(s->mode==4){if(!s->type&&s->timer==16){minion_mode(g,1);minion_texture(g,6);ip->physics.vel_air=(Vec3f){ip->lr*8,40,0};func_800269C0_275C0(0x44A);}else if(s->type==1){if(s->timer>=17&&s->timer<=20){GObj *parent=s->timer==17?g:s->beam;if(parent&&(parent==g||sonic_live(parent,nGCCommonLinkIDWeapon))){if(s->timer==17){minion_texture(g,6);ip->damage_coll.hitstatus=nGMHitStatusNone;func_800269C0_275C0(0x40);}s->beam=doo_beam(g,parent);}}if(s->timer>=60)minion_mode(g,3);}}
 return FALSE;}
static void minion_fall(GObj *g){minion_mode(g,1);}
static sb32 minion_map(GObj *g){ITStruct *ip=itGetStruct(g);DededeMinion *s=MINION(ip);if(!s->mode||s->mode==5)return FALSE;if(s->mode!=1){itMapCheckLRWallProcNoFloor(g,minion_fall);if(ip->coll_data.mask_curr&(MAP_FLAG_LWALL|MAP_FLAG_RWALL)){ip->lr=-ip->lr;ip->physics.vel_air.x=ip->lr*15;}return FALSE;}int hit=itMapTestAllCollisionFlag(g,MAP_FLAG_MAIN_MASK);float rotation=DObjGetStruct(g)->rotate.vec.f.z;itMapCheckCollideAllRebound(g,MAP_FLAG_MAIN_MASK,s->type==2?0.95F:0.3F,NULL);DObjGetStruct(g)->rotate.vec.f.z=rotation;if(hit){if(s->type==2){if(!(ip->coll_data.mask_curr&MAP_FLAG_FLOOR)||ABSF(ip->physics.vel_air.y)<32){s->mode=5;ip->physics.vel_air=(Vec3f){0,0,0};ip->damage_coll.hitstatus=nGMHitStatusNone;ip->attack_coll.damage=5;ip->coll_data.map_coll=(MPObjectColl){30,0,-30,30};itMSBombAttachedUpdateSurface(g);DObjGetStruct(g)->rotate.vec.f.z=rotation;ip->is_attach_surface=TRUE;func_800269C0_275C0(0x107);}}else if(ip->coll_data.mask_curr&MAP_FLAG_FLOOR){minion_mode(g,2);ip->attack_coll.attack_state=nGMAttackStateNew;}}return FALSE;}
static sb32 minion_hit(GObj *g){ITStruct *ip=itGetStruct(g);DededeMinion *s=MINION(ip);if(s->type==2){if(s->mode==5){s->refresh=16;return FALSE;}ip->physics.vel_air.x*=-0.5F;ip->physics.vel_air.y=ABSF(ip->physics.vel_air.y)*0.5F+5;s->refresh=16;return FALSE;}float speed=sqrtf(SQUARE(ip->physics.vel_air.x)+SQUARE(ip->physics.vel_air.y));minion_mode(g,1);ip->attack_coll.attack_state=nGMAttackStateOff;if(!s->trade){ip->physics.vel_air.x=0;ip->physics.vel_air.y=speed*0.5F+5;}s->refresh=0;ip->lifetime=MAX(12,ip->lifetime-(int)(speed*1.5F));return FALSE;}
static sb32 minion_damage(GObj *g){ITStruct *ip=itGetStruct(g);DededeMinion *s=MINION(ip);minion_mode(g,1);float speed=ip->damage_queue*4+10,angle=ip->damage_angle==361?F_CST_DTOR32(45):F_CST_DTOR32(ip->damage_angle);s->terminal=speed;ip->physics.vel_air=(Vec3f){cosf(angle)*speed*-ip->damage_lr,sinf(angle)*speed,0};ip->owner_gobj=ip->damage_gobj;if(sonic_live(ip->damage_gobj,nGCCommonLinkIDFighter)){FTStruct *fp=ftGetStruct(ip->damage_gobj);ip->player=fp->player;ip->team=fp->team;}s->refresh=16;s->trade=1;ip->lifetime=MAX(20,ip->lifetime-ip->damage_queue*8);return FALSE;}
static GObj *minion_make(GObj *f,int type){Vec3f p=DObjGetStruct(f)->translate.vec.f,v={0,0,0};ITDesc d={0};d.kind=nITKindCapsule;d.p_file=&main_files[64][5];d.o_attributes=type==2?0x120:type==1?0xB0:0x40;d.transform_types=(DObjTransformTypes){0x1B,0,0};d.proc_update=minion_update;d.proc_map=minion_map;d.proc_hit=d.proc_shield=minion_hit;d.proc_hop=itMainCommonProcHop;d.proc_reflector=itMainCommonProcReflector;d.proc_damage=minion_damage;GObj *g=itManagerMakeItem(f,&d,&p,&v,ITEM_FLAG_PARENT_FIGHTER);if(!g)return NULL;ITStruct *ip=itGetStruct(g);memset(&ip->item_vars,0,sizeof(ip->item_vars));MINION(ip)->type=type;MINION(ip)->terminal=48;MINION(ip)->creator=f;ip->owner_gobj=f;ip->player=ftGetStruct(f)->player;ip->team=ftGetStruct(f)->team;ip->proc_dead=minion_dead;ip->is_allow_pickup=FALSE;ip->attack_coll.attack_state=nGMAttackStateOff;ip->damage_coll.hitstatus=nGMHitStatusNone;gcAddXObjForDObjFixed(DObjGetStruct(g),0x2E,0);return g;}
static void minion_throw(GObj *g,GObj *f){ITStruct *ip=itGetStruct(g);FTStruct *fp=ftGetStruct(f);float angle=0.872665F-fp->input.pl.stick_range.x*fp->lr*0.0078125F;minion_mode(g,1);ip->lr=fp->lr;ip->physics.vel_air=(Vec3f){48*cosf(angle)*fp->lr,48*sinf(angle),0};ip->lifetime=MINION(ip)->type==2?220:480;ip->damage_coll.hitstatus=nGMHitStatusNormal;if(MINION(ip)->type==2)ip->attack_coll.damage=18;DObjGetStruct(g)->translate.vec.f.y-=200;DObjGetStruct(g)->translate.vec.f.z=0;int count=0;GObj *oldest=NULL;for(GObj *it=gGCCommonLinks[nGCCommonLinkIDItem];it;it=it->link_next)if(it!=g&&minion_is(it)&&MINION(itGetStruct(it))->creator==f&&MINION(itGetStruct(it))->mode){oldest=it;count++;}if(count>=2&&oldest)itGetStruct(oldest)->lifetime=1;}
static void dedede_minion_clear(GObj *g){FTStruct *fp=ftGetStruct(g);GObj *m=DEDEDE(fp)->minion;DEDEDE(fp)->minion=NULL;if(minion_is(m)&&MINION(itGetStruct(m))->creator==g){minion_dead(m);itMainDestroyItem(m);}}
static void dedede_d_damage(GObj *g){DEDEDE(ftGetStruct(g))->charge=0;dedede_minion_clear(g);}
static void dedede_minion_attach(GObj *g){FTStruct *fp=ftGetStruct(g);dedede_minion_clear(g);DEDEDE(fp)->minion=minion_make(g,DEDEDE(fp)->charge);}
static void dedede_d_state(GObj *g,int phase){FTStruct *fp=ftGetStruct(g);marth_clear_flags(fp);dedede_enter(g,(fp->ga==nMPKineticsAir?251:248)+phase,2);fp->proc_damage=dedede_d_damage;if(phase==1)DEDEDE(fp)->timer=0;if(phase==2&&!minion_is(DEDEDE(fp)->minion))dedede_minion_attach(g);}
static void dedede_down(GObj *g){dedede_d_state(g,0);}
static void dedede_d_update(GObj *g){FTStruct *fp=ftGetStruct(g);int phase=(fp->status_id-248)%3;if(!phase){if(g->anim_frame<=0)dedede_d_state(g,DEDEDE(fp)->charge==2?2:1);}else if(phase==1){int t=++DEDEDE(fp)->timer;if(t==6||t==60||t==115)dedede_minion_attach(g);else if(t==32||t==87)dedede_minion_clear(g);else if(t==54||t==109){if(DEDEDE(fp)->charge<2)DEDEDE(fp)->charge++;}if(DEDEDE(fp)->charge==2&&g->anim_frame>=20){dedede_minion_clear(g);mpCommonSetFighterWaitOrFall(g);}}else{if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=0;GObj *m=DEDEDE(fp)->minion;if(minion_is(m))minion_throw(m,g);DEDEDE(fp)->minion=NULL;DEDEDE(fp)->charge=0;}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}}
static void dedede_d_interrupt(GObj *g){FTStruct *fp=ftGetStruct(g);if(DEDEDE(fp)->timer>=12&&!(fp->input.pl.button_hold&fp->input.button_mask_b)){dedede_d_state(g,2);return;}if(fp->input.pl.button_tap&fp->input.button_mask_z){dedede_minion_clear(g);mpCommonSetFighterWaitOrFall(g);}}
static void dedede_d_air(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id+3;mpCommonSetFighterAir(fp);ftMainSetStatus(g,a,g->anim_frame,1,2);fp->proc_damage=dedede_d_damage;ftPhysicsClampAirVelXMax(fp);}
static void dedede_d_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id-3;mpCommonSetFighterGround(fp);ftMainSetStatus(g,a,g->anim_frame,1,2);fp->proc_damage=dedede_d_damage;}
static void dedede_d_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,dedede_d_air);else mpCommonProcFighterLanding(g,dedede_d_ground);}
static void dedede_down_install(FighterDescriptor *d){for(int a=248;a<=253;a++){FTStatusDesc *s=dedede_status+a-220;s->mflags.motion_id=a-25;s->mflags.attack_id=s->sflags.attack_id=19;s->sflags.ga=a>=251;s->proc_update=dedede_d_update;s->proc_interrupt=a==249||a==252?dedede_d_interrupt:NULL;s->proc_physics=a>=251?ftPhysicsApplyAirVelDrift:ftPhysicsApplyGroundVelTransN;s->proc_map=dedede_d_map;}d->special_handler[2]=d->special_handler[5]=dedede_down;}
