/* MarinaSpecial.asm. Command grab and recovery; Clanpot item logic follows. */
static FTStatusDesc marina_status[64];
static struct {int turn,charge,buffer,pending;} marina_state[4];
#define MARINA_STATE(fp) (&marina_state[(fp)->player])
static void marina_enter(GObj *g,int a){remix_copy_set(g,63,a,0,1,0);ftMainPlayAnimEventsAll(g);}
static void marina_pull(GObj *g){FTStruct *fp=ftGetStruct(g);int air=fp->ga==nMPKineticsAir;marth_clear_flags(fp);remix_copy_set(g,63,air?231:226,0,1,2);ftMainPlayAnimEventsAll(g);ftParamSetCaptureImmuneMask(fp,FTCATCHKIND_MASK_ALL);fp->catch_gobj=fp->search_gobj;MARINA_STATE(fp)->turn=0;if(air){fp->physics.vel_air.x*=0.5F;fp->physics.vel_air.y=0;}}
static void marina_n(GObj *g){FTStruct *fp=ftGetStruct(g);marth_clear_flags(fp);marina_enter(g,fp->ga==nMPKineticsGround?225:230);ftYoshiSpecialNSetCatchParams(fp,marina_pull);fp->is_fastfall=FALSE;}
static void marina_throw_enter(GObj *g){FTStruct *fp=ftGetStruct(g);int air=fp->ga==nMPKineticsAir,y=fp->input.pl.stick_range.y,a=air?232:227;if(y>=40)a++;else if(y<=-40)a+=2;else if(fp->input.pl.stick_range.x*fp->lr<=-40){fp->lr=-fp->lr;MARINA_STATE(fp)->turn=air?6:8;}remix_copy_set(g,63,a,0,1,2);ftMainPlayAnimEventsAll(g);if(air)fp->physics.vel_air.x=fp->physics.vel_air.y=0;}
static void marina_pull_update(GObj *g){if(g->anim_frame<=0)marina_throw_enter(g);}
static void marina_throw_turn(GObj *g){FTStruct *fp=ftGetStruct(g);if(MARINA_STATE(fp)->turn){int n=--MARINA_STATE(fp)->turn;fp->joints[nFTPartsJointTopN]->rotate.vec.f.y=fp->lr*(1.570796327F-3.141592654F*n/8);}}
static void marina_n_physics(GObj *g){FTStruct *fp=ftGetStruct(g);int phase=fp->motion_vars.flags.flag2;if(fp->ga==nMPKineticsGround){if(phase==1){fp->physics.vel_ground.x=60;fp->motion_vars.flags.flag2=phase=2;}if(phase==2)ftPhysicsSetGroundVelTransferAir(g);else if(phase==3){ftPhysicsSetGroundVelFriction(fp,dMPCollisionMaterialFrictions[fp->coll_data.floor_flags&MAP_VERTEX_MAT_MASK]);ftPhysicsSetGroundVelTransferAir(g);}else ftPhysicsApplyGroundVelFriction(g);}else{if(phase==1){fp->physics.vel_air.x=48*fp->lr;fp->physics.vel_air.y=0;fp->motion_vars.flags.flag2=2;}else if(phase==3){FTAttributes a=*fp->attr;a.air_friction=3;ftPhysicsApplyGravityDefault(fp,fp->attr);ftPhysicsApplyAirVelXFriction(fp,&a);}else if(phase==4)ftPhysicsApplyAirVelDriftFastFall(g);else if(phase!=2)ftPhysicsApplyAirVelFriction(g);}}
static void marina_throw_physics(GObj *g){FTStruct *fp=ftGetStruct(g);if(!fp->motion_vars.flags.flag0)return;ftPhysicsApplyGravityClampTVel(fp,2,fp->attr->tvel_base);if(!ftPhysicsCheckClampAirVelXDecMax(fp,fp->attr)){ftPhysicsClampAirVelXStickRange(fp,8,fp->attr->air_accel,fp->attr->air_speed_max_x);ftPhysicsApplyAirVelXFriction(fp,fp->attr);}}
static void marina_n_air(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,63)+5;mpCommonSetFighterAir(fp);remix_copy_set(g,63,a,g->anim_frame,1,2);if(a==230)ftYoshiSpecialNSetCatchParams(fp,marina_pull);}
static void marina_n_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,63)-5;mpCommonSetFighterGround(fp);remix_copy_set(g,63,a,g->anim_frame,1,2);if(a==225)ftYoshiSpecialNSetCatchParams(fp,marina_pull);}
static void marina_n_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround){if(remix_copy_current(fp,63)==225)mpCommonProcFighterOnFloor(g,marina_n_air);else mpCommonProcFighterOnEdge(g,marina_n_air);}else mpCommonProcFighterLanding(g,marina_n_ground);}
static void marina_throw_land(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->catch_gobj)ftCommonCatchCaptureSetStatusRelease(g);mpCommonSetFighterWaitOrLanding(g);}
static void marina_throw_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)ftCommonCatchProcMap(g);else mpCommonProcFighterLanding(g,marina_throw_land);}
static void marina_up(GObj *g){FTStruct *fp=ftGetStruct(g);int air=fp->ga==nMPKineticsAir;marth_clear_flags(fp);marina_enter(g,air?253:252);fp->motion_vars.flags.flag2=1;if(air){fp->is_fastfall=FALSE;fp->physics.vel_air.y=fp->attr->gravity;}}
static void marina_up_update(GObj *g){if(g->anim_frame<=0)ftCommonFallSpecialSetStatus(g,1,FALSE,TRUE,FALSE,0.375F,FALSE);}
static void marina_up_physics(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround){ftPhysicsApplyGroundVelFriction(g);return;}int phase=fp->motion_vars.flags.flag2;ftPhysicsApplyGravityDefault(fp,fp->attr);if(!ftPhysicsCheckClampAirVelXDecMax(fp,fp->attr)){if(phase==3)ftPhysicsClampAirVelXStickRange(fp,8,0.0166015625F,22);ftPhysicsApplyAirVelXFriction(fp,fp->attr);}if(phase==1&&fp->status_id!=252){fp->physics.vel_air.x*=0.875F;fp->physics.vel_air.y=0;}if(phase==2){fp->physics.vel_air.x=10*fp->lr;fp->physics.vel_air.y=fp->status_id==252?98:92;fp->motion_vars.flags.flag2=3;fp->jumps_used=fp->attr->jumps_max;}}
static void marina_up_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround){mpCommonSetFighterFallOnEdgeBreak(g);return;}if(fp->physics.vel_air.y>=0)mpCommonCheckFighterProject(g);else if(mpCommonCheckFighterPassCliff(g,ftSamusSpecialHiProcPass)){if(fp->coll_data.mask_stat&MAP_FLAG_CLIFF_MASK)ftCommonCliffCatchSetStatus(g);else ftCommonLandingFallSpecialSetStatus(g,FALSE,0.375F);}}
static void marina_install(FighterDescriptor *d){memcpy(marina_status,safe_statuses,sizeof(marina_status));for(int a=225;a<=253;a++){if(a>=235&&a<252)continue;FTStatusDesc *s=marina_status+a-220;int air=a>=230&&a!=252,pull=a==226||a==231,throwing=a==227||a==228||a==229||a==232||a==233||a==234,up=a>=252;s->mflags.motion_id=a-25;s->mflags.attack_id=up?17:18;s->sflags.attack_id=s->mflags.attack_id;s->sflags.ga=air;s->proc_update=up?marina_up_update:pull?marina_pull_update:throwing?ftCommonThrowProcUpdate:air?ftAnimEndSetFall:ftAnimEndSetWait;s->proc_interrupt=up?wolf_up_turn:a==227||a==232?marina_throw_turn:NULL;s->proc_physics=up?marina_up_physics:a==225||a==230?marina_n_physics:air?(throwing?marina_throw_physics:ftPhysicsApplyAirVelFriction):ftPhysicsApplyGroundVelFriction;s->proc_map=up?marina_up_map:throwing?marina_throw_map:marina_n_map;}
 d->special_descs=marina_status;d->special_handler[0]=d->special_handler[3]=marina_n;d->special_handler[1]=d->special_handler[4]=marina_up;
}

static FTSpecialColl marina_absorb_coll={99,0,{0,500,450},{650,650,650},0x18000000};
static int marina_d_base(FTStruct *fp){return fp->ga==nMPKineticsAir?261:254;}
static void marina_d_shield(FTStruct *fp){fp->is_reflect=TRUE;fp->special_coll=&marina_absorb_coll;}
static void marina_d_state(GObj *g,int phase){FTStruct *fp=ftGetStruct(g);marth_clear_flags(fp);ftMainSetStatus(g,marina_d_base(fp)+phase,0,1,phase==1||phase==2?0x804:0);ftMainPlayAnimEventsAll(g);if(phase==1||phase==2)marina_d_shield(fp);}
static void marina_d_pull(GObj *g){FTStruct *fp=ftGetStruct(g);marina_d_state(g,MARINA_STATE(fp)->charge?4:5);fp->motion_vars.flags.flag0=0;}
static void marina_down(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->item_gobj&&MARINA_STATE(fp)->charge==4)return;MARINA_STATE(fp)->buffer=-1;MARINA_STATE(fp)->pending=0;marina_d_state(g,fp->item_gobj?6:0);if(!fp->item_gobj){fp->status_vars.ness.speciallw.release_lag=FTNESS_PSYCHICMAGNET_RELEASE_LAG;fp->status_vars.ness.speciallw.is_release=FALSE;fp->status_vars.ness.speciallw.gravity_delay=FTNESS_PSYCHICMAGNET_GRAVITY_DELAY;fp->is_absorb=FALSE;}}
static void marina_d_buffer(FTStruct *fp){int *b=&MARINA_STATE(fp)->buffer;if(*b<0)*b=0;else if(fp->input.pl.button_tap&fp->input.button_mask_b)*b=1;}
static int marina_item_level(ITStruct *ip){int c=clan_is(ip);if(c)return c;if(turnip_is(ip))return ip->attack_coll.damage==30?4:ip->attack_coll.damage==12?3:ip->attack_coll.damage==6?2:1;static const u8 levels[]={2,2,1,1,0,0,0,2,2,1,2,1,1,4,4,4,1,1,2,2,1,1,0,0,0,0,2};return ip->kind>=0&&ip->kind<sizeof(levels)?levels[ip->kind]:0;}
static void marina_d_absorbed(GObj *g,int charge){FTStruct *fp=ftGetStruct(g);MARINA_STATE(fp)->charge+=charge;if(MARINA_STATE(fp)->charge>4)MARINA_STATE(fp)->charge=4;marina_d_state(g,2);}
int port_remix_marina_absorb_weapon(GObj *g){WPStruct *wp=wpGetStruct(g);GObj *fighter=wp->reflect_gobj;if(!port_remix_enabled()||!fighter)return 0;FTStruct *fp=ftGetStruct(fighter);if(fp->fkind!=63||fp->special_coll!=&marina_absorb_coll)return 0;int charge=1;if(wp->kind==nWPKindChargeShot&&wp->port_remix_origin!=57&&wp->port_remix_origin!=34){int n=wp->weapon_vars.charge_shot.charge_size;charge=n==7?3:n>=4?2:1;}else if(wp->kind==nWPKindEggThrow||wp->kind==nWPKindBoomerang||wp->kind==nWPKindThunderHead||wp->kind==nWPKindThunderTrail)charge=2;fp->lr=DObjGetStruct(g)->translate.vec.f.x>=DObjGetStruct(fighter)->translate.vec.f.x?1:-1;marina_d_absorbed(fighter,charge);if(wp->proc_absorb&&wp->proc_absorb(g))return 1;if(wp->proc_dead)wp->proc_dead(g);return 1;}
int port_remix_marina_absorb_item(GObj *g){ITStruct *ip=itGetStruct(g);GObj *fighter=ip->reflect_gobj;if(!port_remix_enabled()||!fighter)return 0;FTStruct *fp=ftGetStruct(fighter);if(fp->fkind!=63||fp->special_coll!=&marina_absorb_coll)return 0;fp->lr=DObjGetStruct(g)->translate.vec.f.x>=DObjGetStruct(fighter)->translate.vec.f.x?1:-1;marina_d_absorbed(fighter,marina_item_level(ip));if(ip->proc_dead)ip->proc_dead(g);return 1;}
static void marina_d_update(GObj *g){FTStruct *fp=ftGetStruct(g);int phase=fp->status_id-marina_d_base(fp),tap=fp->input.pl.button_tap&fp->input.button_mask_b;switch(phase){
 case 0:marina_d_buffer(fp);if(fp->motion_vars.flags.flag1&&MARINA_STATE(fp)->charge==4){marina_d_pull(g);return;}if(g->anim_frame<=0)marina_d_state(g,1);break;
 case 1:if(tap||MARINA_STATE(fp)->buffer){marina_d_pull(g);return;}ftNessSpecialLwCheckRelease(fp);ftNessSpecialLwDecReleaseLag(fp);if(fp->status_vars.ness.speciallw.release_lag<=0&&fp->status_vars.ness.speciallw.is_release)marina_d_state(g,3);break;
 case 2:marina_d_buffer(fp);if(fp->motion_vars.flags.flag1){if(MARINA_STATE(fp)->buffer){marina_d_pull(g);return;}if(!(fp->input.pl.button_hold&fp->input.button_mask_b)){marina_d_state(g,3);return;}}if(g->anim_frame<=0)marina_d_state(g,1);break;
 case 3:if(tap){marina_d_pull(g);return;}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);break;
 case 4:if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=0;if(!fp->item_gobj){GObj *item=clan_make(g,MARINA_STATE(fp)->charge);if(item)itMainSetFighterHold(item,g);}MARINA_STATE(fp)->charge=0;}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);break;
 case 6:if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=0;if(fp->item_gobj){GObj *item=fp->item_gobj;MARINA_STATE(fp)->charge+=marina_item_level(itGetStruct(item));if(MARINA_STATE(fp)->charge>4)MARINA_STATE(fp)->charge=4;fp->item_gobj=NULL;itMainDestroyItem(item);}}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);break;
 default:if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);break;
 }}
static void marina_d_air(GObj *g){FTStruct *fp=ftGetStruct(g);int phase=fp->status_id-254;mpCommonSetFighterAir(fp);ftMainSetStatus(g,261+phase,g->anim_frame,1,0x804);if(phase==1||phase==2)marina_d_shield(fp);}
static void marina_d_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int phase=fp->status_id-261;mpCommonSetFighterGround(fp);ftMainSetStatus(g,254+phase,g->anim_frame,1,0x804);if(phase==1||phase==2)marina_d_shield(fp);}
static void marina_d_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,marina_d_air);else mpCommonProcFighterLanding(g,marina_d_ground);}
static void marina_down_install(FighterDescriptor *d){clan_install();for(int a=254;a<=267;a++){FTStatusDesc *s=marina_status+a-220;s->mflags.motion_id=a-25;s->mflags.attack_id=s->sflags.attack_id=30;s->sflags.ga=a>=261;s->proc_update=marina_d_update;s->proc_interrupt=NULL;s->proc_physics=a>=261?ftPhysicsApplyAirVelDrift:ftPhysicsApplyGroundVelFriction;s->proc_map=marina_d_map;}d->special_handler[2]=d->special_handler[5]=marina_down;}

void port_remix_marina_tick(GObj *g){FTStruct *fp=ftGetStruct(g);if(port_remix_enabled()&&fp->fkind==63&&fp->status_id<nFTCommonStatusWait)memset(MARINA_STATE(fp),0,sizeof(marina_state[0]));}
