/* SheikSpecial.asm: Needle Storm, Vanish and Bouncing Fish. */
static FTStatusDesc sheik_status[64];
static struct {int needles,charge_timer,release,timer,fish_used,buffer;float angle;} sheik_state[4];
#define SHEIK_STATE(fp) (&sheik_state[(fp)->player])
void port_remix_sheik_tick(GObj *g){FTStruct *fp=ftGetStruct(g);if(port_remix_enabled()&&fp->fkind==62){if(fp->ga==nMPKineticsGround)SHEIK_STATE(fp)->fish_used=0;if(fp->status_id<7)memset(SHEIK_STATE(fp),0,sizeof(sheik_state[0]));}}
void port_remix_sheik_contact(FTStruct *fp,int type){if(port_remix_enabled()&&fp->fkind==62&&fp->status_id==241&&(type==nGMHitTypeDamage||type==nGMHitTypeShield||type==nGMHitTypeAttack))fp->motion_vars.flags.flag0=1;}
static void sheik_enter(GObj *g,int a){remix_copy_set(g,62,a,0,1,0);ftMainPlayAnimEventsAll(g);}
static void sheik_needle_damage(GObj *g){SHEIK_STATE(ftGetStruct(g))->needles=0;}
static sb32 sheik_needle_hit(GObj *g){efManagerDustExpandSmallMakeEffect(&DObjGetStruct(g)->translate.vec.f,1);return TRUE;}
static sb32 sheik_needle_update(GObj *g){return wpMainDecLifeCheckExpire(wpGetStruct(g))?sheik_needle_hit(g):FALSE;}
static void sheik_needle(GObj *g){FTStruct *fp=ftGetStruct(g);Vec3f p={0,0,0};gmCollisionGetFighterPartsWorldPosition(fp->joints[15],&p);p.z=0;WPDesc d={0};d.kind=nWPKindLGunAmmo;d.p_weapon=&main_files[62][5];d.transform_types=(DObjTransformTypes){0x12,0x47,0};d.proc_update=sheik_needle_update;d.proc_map=itLGunWeaponAmmoProcMap;d.proc_hit=d.proc_shield=d.proc_setoff=d.proc_absorb=sheik_needle_hit;d.proc_hop=wpBossBulletProcHop;d.proc_reflector=wpSamusBombProcReflector;GObj *w=wpManagerMakeWeapon(g,&d,&p,WEAPON_FLAG_PARENT_FIGHTER);if(!w)return;WPStruct *wp=wpGetStruct(w);wp->lifetime=18;float a=fp->ga==nMPKineticsAir?-0.785398F:0;wp->physics.vel_air=(Vec3f){225*cosf(a)*fp->lr,225*sinf(a),0};wpMainVelSetModelPitch(w);func_800269C0_275C0(0x410);}
static void sheik_shoot(GObj *g){FTStruct *fp=ftGetStruct(g);if(!SHEIK_STATE(fp)->needles)SHEIK_STATE(fp)->needles=1;fp->motion_vars.flags.flag0=0;sheik_enter(g,fp->ga==nMPKineticsAir?239:236);fp->proc_damage=sheik_needle_damage;}
static void sheik_n(GObj *g){FTStruct *fp=ftGetStruct(g);sheik_enter(g,fp->ga==nMPKineticsAir?237:234);SHEIK_STATE(fp)->release=SHEIK_STATE(fp)->needles==6;fp->proc_damage=sheik_needle_damage;}
static void sheik_n_begin_update(GObj *g){if(g->anim_frame>0)return;FTStruct *fp=ftGetStruct(g);if(SHEIK_STATE(fp)->release)sheik_shoot(g);else{sheik_enter(g,fp->ga==nMPKineticsAir?238:235);SHEIK_STATE(fp)->charge_timer=18;fp->proc_damage=sheik_needle_damage;}}
static void sheik_n_interrupt(GObj *g){FTStruct *fp=ftGetStruct(g);int tap=fp->input.pl.button_tap,begin=remix_copy_current(fp,62)==234||remix_copy_current(fp,62)==237;if(tap&(fp->input.button_mask_a|fp->input.button_mask_b)){if(begin)SHEIK_STATE(fp)->release=1;else{sheik_shoot(g);return;}}if(!begin&&fp->ga==nMPKineticsGround){int escape=ftCommonEscapeGetStatus(fp);if(escape!=-1){ftCommonEscapeSetStatus(g,escape,0);return;}}if(tap&fp->input.button_mask_z)mpCommonSetFighterWaitOrFall(g);}
static void sheik_charge_update(GObj *g){FTStruct *fp=ftGetStruct(g);__typeof__(sheik_state[0]) *s=SHEIK_STATE(fp);if(!--s->charge_timer){s->charge_timer=18;if(s->needles<6&&++s->needles==6)mpCommonSetFighterWaitOrFall(g);}}
static void sheik_shoot_update(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=0;if(SHEIK_STATE(fp)->needles){SHEIK_STATE(fp)->needles--;sheik_needle(g);}}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}
static void sheik_n_air(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,62)+3;mpCommonSetFighterAir(fp);remix_copy_set(g,62,a,g->anim_frame,1,0x800);fp->proc_damage=sheik_needle_damage;}
static void sheik_n_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,62)-3;mpCommonSetFighterGround(fp);remix_copy_set(g,62,a,g->anim_frame,1,0x800);fp->proc_damage=sheik_needle_damage;}
static void sheik_n_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,sheik_n_air);else if(remix_copy_current(fp,62)==239)mpCommonProcFighterWaitOrLanding(g);else mpCommonProcFighterLanding(g,sheik_n_ground);}
static void sheik_up(GObj *g){FTStruct *fp=ftGetStruct(g);marth_clear_flags(fp);sheik_enter(g,fp->ga==nMPKineticsGround?228:231);if(fp->ga==nMPKineticsGround)fp->physics.vel_ground.x*=0.5F;else{fp->physics.vel_air.x*=0.5F;fp->physics.vel_air.y=75;fp->is_fastfall=FALSE;}}
static void sheik_up_move_physics(GObj *g){FTStruct *fp=ftGetStruct(g);__typeof__(sheik_state[0]) *s=SHEIK_STATE(fp);if(s->timer>=6)return;float x=280*cosf(s->angle);fp->physics.vel_air.x=x*fp->lr;if(fp->ga==nMPKineticsGround)fp->physics.vel_ground.x=x;else fp->physics.vel_air.y=280*sinf(s->angle);}
static void sheik_up_begin_update(GObj *g){if(g->anim_frame>0)return;FTStruct *fp=ftGetStruct(g);int x=fp->input.pl.stick_range.x,y=fp->input.pl.stick_range.y,ground=fp->ga==nMPKineticsGround,dead=x*x+y*y<121;if(ABSF(x)>=11)fp->lr=x>0?1:-1;if(dead||!ground||y||!x)mpCommonSetFighterAir(fp);SHEIK_STATE(fp)->angle=dead?1.570796327F:syUtilsArcTan2(y,x*fp->lr);fp->physics.vel_air.x=fp->physics.vel_air.y=fp->physics.vel_ground.x=0;sheik_enter(g,fp->ga==nMPKineticsGround?229:232);SHEIK_STATE(fp)->timer=12;fp->jumps_used=fp->attr->jumps_max;mewtwo_hide(g);if(ground)fp->coll_data.ignore_line_id=fp->coll_data.floor_line_id;}
static void sheik_up_move_update(GObj *g){FTStruct *fp=ftGetStruct(g);if(--SHEIK_STATE(fp)->timer)return;sheik_enter(g,fp->ga==nMPKineticsGround?230:233);if(fp->ga==nMPKineticsGround)fp->physics.vel_ground.x*=0.25F;else{fp->physics.vel_air.x*=0.109375F;fp->physics.vel_air.y*=0.109375F;fp->motion_vars.flags.flag1=0;}}
static void sheik_up_end_update(GObj *g){FTStruct *fp=ftGetStruct(g);fp->is_invisible=fp->motion_vars.flags.flag2!=0;if(g->anim_frame<=0){if(fp->ga==nMPKineticsGround)ftCommonWaitSetStatus(g);else ftCommonFallSpecialSetStatus(g,0.9375F,FALSE,TRUE,FALSE,0.5F,TRUE);}}
static void sheik_up_end_physics(GObj *g){if(ftGetStruct(g)->motion_vars.flags.flag1)ftPhysicsApplyAirVelDrift(g);else ftPhysicsApplyAirVelFriction(g);}
static void sheik_up_air(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id+3;mpCommonSetFighterAir(fp);ftMainSetStatus(g,a,g->anim_frame,1,0);if(a==232)mewtwo_hide(g);}
static void sheik_up_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id-3;mpCommonSetFighterGround(fp);ftMainSetStatus(g,a,g->anim_frame,1,0);if(a==229)mewtwo_hide(g);}
static void sheik_up_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,sheik_up_air);else mpCommonProcFighterLanding(g,sheik_up_ground);}
static void sheik_up_end_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround){mpCommonSetFighterFallOnEdgeBreak(g);return;}if(fp->physics.vel_air.y>=0)mpCommonCheckFighterProject(g);else if(mpCommonCheckFighterPassCliff(g,ftSamusSpecialHiProcPass)){if(fp->coll_data.mask_stat&MAP_FLAG_CLIFF_MASK)ftCommonCliffCatchSetStatus(g);else ftCommonLandingFallSpecialSetStatus(g,FALSE,0.3695068359375F);}}
static void sheik_fish_damage(GObj *g){SHEIK_STATE(ftGetStruct(g))->fish_used=0;}
static void sheik_down(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterAir(fp);marth_clear_flags(fp);sheik_enter(g,240);if(!SHEIK_STATE(fp)->fish_used)fp->physics.vel_air.y=50;SHEIK_STATE(fp)->fish_used=1;SHEIK_STATE(fp)->buffer=0;fp->proc_damage=sheik_fish_damage;fp->motion_vars.flags.flag2=1;fp->is_fastfall=FALSE;}
static void sheik_fish_attack(GObj *g){ftMainSetStatus(g,241,0,1,3);ftMainPlayAnimEventsAll(g);}
static void sheik_fish_update(GObj *g){FTStruct *fp=ftGetStruct(g);int tap=fp->input.pl.button_tap&fp->input.button_mask_b,buffer=tap|SHEIK_STATE(fp)->buffer;SHEIK_STATE(fp)->buffer=tap;if(g->anim_frame<=0){if(fp->status_id==240)sheik_fish_attack(g);else ftCommonFallSetStatus(g);return;}if(fp->status_id==240&&g->anim_frame>10&&buffer)sheik_fish_attack(g);else if(fp->status_id==243&&g->anim_frame<=40&&g->anim_frame>15&&buffer){fp->lr=-fp->lr;sheik_fish_attack(g);}}
static void sheik_fish_physics(GObj *g){FTStruct *fp=ftGetStruct(g);int recoil=fp->status_id==243;ftPhysicsApplyGravityClampTVel(fp,fp->attr->gravity*(fp->motion_vars.flags.flag1?1:0.23F),fp->attr->tvel_base);int clamped=ftPhysicsCheckClampAirVelXDecMax(fp,fp->attr);if(clamped&&!recoil)return;int x=fp->input.pl.stick_range.x,dir=fp->lr*(recoil?-1:1);float speed=ABSF(x)<8?(recoil?30:40):fp->physics.vel_air.x*dir+x*fp->lr;if(speed<20)speed=20;if(speed>40)speed=40;fp->physics.vel_air.x=speed*dir;}
static void sheik_fish_land(GObj *g){mpCommonSetFighterGround(ftGetStruct(g));sheik_enter(g,242);}
static void sheik_fish_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->status_id==241){if(fp->coll_data.mask_curr&(MAP_FLAG_LWALL|MAP_FLAG_RWALL))fp->motion_vars.flags.flag0=1;if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=fp->motion_vars.flags.flag1=0;fp->physics.vel_air.y=65;sheik_enter(g,243);return;}mpCommonProcFighterCliff(g,sheik_fish_land);}else mpCommonProcFighterLanding(g,sheik_fish_land);}
static void sheik_install(FighterDescriptor *d){memcpy(sheik_status,safe_statuses,sizeof(sheik_status));for(int a=228;a<=243;a++){FTStatusDesc *s=sheik_status+a-220;int air=a>=231&&a!=234&&a!=235&&a!=236&&a!=242;s->mflags.motion_id=a-25;s->mflags.attack_id=a<234?17:a<240?18:19;s->sflags.attack_id=s->mflags.attack_id;s->sflags.ga=air;s->proc_update=a==228||a==231?sheik_up_begin_update:a==229||a==232?sheik_up_move_update:a==230||a==233?sheik_up_end_update:a==234||a==237?sheik_n_begin_update:a==235||a==238?sheik_charge_update:a==236||a==239?sheik_shoot_update:a==240||a==243?sheik_fish_update:air?ftAnimEndSetFall:ftAnimEndSetWait;s->proc_interrupt=a==234||a==235||a==237||a==238?sheik_n_interrupt:NULL;s->proc_physics=a==229||a==232?sheik_up_move_physics:a==233?sheik_up_end_physics:a==240||a==241||a==243?sheik_fish_physics:a==242?ftPhysicsApplyGroundFrictionOrTransN:!air?ftPhysicsApplyGroundVelFriction:a==231||a==237?ftPhysicsApplyAirVelDrift:ftPhysicsApplyAirVelFriction;s->proc_map=a==230||a==233?sheik_up_end_map:a<234?sheik_up_map:a<240?sheik_n_map:a==242?mpCommonSetFighterFallOnEdgeBreak:a==243?mpCommonProcFighterCliffWaitOrLanding:sheik_fish_map;}
 d->special_descs=sheik_status;d->special_handler[0]=d->special_handler[3]=sheik_n;d->special_handler[1]=d->special_handler[4]=sheik_up;d->special_handler[2]=d->special_handler[5]=sheik_down;
}
