/* Clanpot's four held items share native pickup/throw plumbing. State is stored
 * in the item so reflections, simultaneous items, and rollback stay independent. */
typedef struct {int type,mode,timer,refresh,cracked,axis;float target,accel;} ClanItem;
#define CLAN(ip) ((ClanItem*)&(ip)->item_vars)
_Static_assert(sizeof(ClanItem)<=sizeof(((ITStruct*)0)->item_vars),"Clanpot item state fits");
static ITStatusDesc clan_status[6];
static int clan_is(ITStruct *ip){if(!port_remix_enabled()||!main_files[63][7]||ip->kind!=nITKindLinkBomb)return 0;for(int n=1;n<=4;n++)if((void*)ip->attr==(char*)main_files[63][7]+0x40+0x50*(n-1))return n;return 0;}
ITStatusDesc *port_remix_clan_item_status(GObj *g,ITStatusDesc *table){return clan_is(itGetStruct(g))?clan_status:table;}
static void clan_fall(GObj *g){ITStruct *ip=itGetStruct(g);CLAN(ip)->mode=-1;ip->attack_coll.attack_state=nGMAttackStateOff;ip->damage_coll.hitstatus=nGMHitStatusNormal;ip->is_allow_pickup=TRUE;ip->lifetime=780;itMapSetAir(ip);itMainSetStatus(g,clan_status,4);}
static void clan_wait(GObj *g){itMainSetGroundAllowPickup(g);itMainSetStatus(g,clan_status,0);}
static sb32 clan_wait_map(GObj *g){itMapCheckLRWallProcNoFloor(g,clan_fall);return FALSE;}
static sb32 clan_fall_map(GObj *g){return itMapCheckDestroyDropped(g,0.4F,0.3F,clan_wait);}
static sb32 clan_fall_update(GObj *g){ITStruct *ip=itGetStruct(g);itMainApplyGravityClampTVel(ip,1.2F,100);return --ip->lifetime<=0;}
static sb32 clan_hold_update(GObj *g){CLAN(itGetStruct(g))->mode=0;return FALSE;}
static void clan_scale(GObj *g,float n){ITStruct *ip=itGetStruct(g);ip->physics.vel_air.x*=n;ip->physics.vel_air.y*=n;}
static void clan_turn(GObj *g){ITStruct *ip=itGetStruct(g);ClanItem *s=CLAN(ip);s->axis=ip->physics.vel_air.x==0;s->target=-(s->axis?ip->physics.vel_air.y:ip->physics.vel_air.x);s->accel=s->target*0.0546875F;s->mode=2;ip->is_thrown=TRUE;}
static void clan_bomb_explode(GObj *g){ITStruct *ip=itGetStruct(g);ip->physics.vel_air=(Vec3f){0,0,0};ip->damage_coll.hitstatus=nGMHitStatusNone;ip->attack_coll.knockback_base=80;ip->attack_coll.knockback_scale=70;ip->attack_coll.attack_state=nGMAttackStateNew;itMainClearOwnerStats(g);DObjGetStruct(g)->flags=DOBJ_FLAG_HIDDEN;itBombHeiExplodeInitVars(g);CLAN(ip)->mode=4;CLAN(ip)->timer=0;efManagerSparkleWhiteMultiExplodeMakeEffect(&DObjGetStruct(g)->translate.vec.f);efManagerQuakeMakeEffect(1);func_800269C0_275C0(1);itMainSetStatus(g,clan_status,5);}
static sb32 clan_bomb_update(GObj *g){ITStruct *ip=itGetStruct(g);itBombHeiCommonUpdateAttackEvent(g);ip->multi++;return ++CLAN(ip)->timer>=6;}
static sb32 clan_destroy(GObj *g){efManagerDustExpandSmallMakeEffect(&DObjGetStruct(g)->translate.vec.f,1);func_800269C0_275C0(0x33);return TRUE;}
static sb32 clan_hit(GObj *g){ITStruct *ip=itGetStruct(g);ClanItem *s=CLAN(ip);if(s->type==4){clan_bomb_explode(g);return FALSE;}if(s->type==1){if(s->cracked)return clan_destroy(g);s->cracked=1;if(DObjGetStruct(g)->mobj)DObjGetStruct(g)->mobj->texture_id_curr=1;ip->physics.vel_air.y=38;ip->physics.vel_air.x*=-0.125F*syUtilsRandFloat();clan_fall(g);}else if(s->type==2){clan_scale(g,0.5F);s->refresh=4;if(s->mode!=2){s->mode=2;s->timer=30;}}else if(s->mode==1){clan_scale(g,-0.9375F);s->mode=3;s->timer=40;}else if(s->mode==2){*(s->axis?&ip->physics.vel_air.y:&ip->physics.vel_air.x)=s->target;clan_scale(g,0.9375F);s->mode=3;s->timer=40;}else clan_scale(g,0.9375F);return FALSE;}
static sb32 clan_damage(GObj *g){ITStruct *ip=itGetStruct(g);ClanItem *s=CLAN(ip);if(s->type==1){if(s->cracked)return clan_destroy(g);s->cracked=1;if(DObjGetStruct(g)->mobj)DObjGetStruct(g)->mobj->texture_id_curr=1;clan_scale(g,-0.25F);clan_fall(g);return FALSE;}if(s->type==4){clan_bomb_explode(g);return FALSE;}clan_scale(g,s->type==3?0.5F:-0.25F);clan_fall(g);return FALSE;}
static sb32 clan_shield(GObj *g){ITStruct *ip=itGetStruct(g);if(CLAN(ip)->type!=3)return clan_hit(g);clan_scale(g,-0.1875F);ip->owner_gobj=NULL;clan_fall(g);return FALSE;}
static sb32 clan_reflect(GObj *g){itMainCommonProcReflector(g);ClanItem *s=CLAN(itGetStruct(g));s->mode=0;itMainSetStatus(g,clan_status,3);return FALSE;}
static int clan_can_catch(FTStruct *fp){int a=fp->status_id;return (a>=nFTCommonStatusWait&&a<=nFTCommonStatusOttotto)||a==nFTCommonStatusFallSpecial||a==nFTCommonStatusLandingFallSpecial||a==nFTCommonStatusStopCeil||(a>=nFTCommonStatusReboundWait&&a<=nFTCommonStatusCliffWait)||(a>=nFTCommonStatusLightThrowDash&&a<=nFTCommonStatusLightThrowAirLw4)||(a>=nFTCommonStatusGuardOn&&a<=nFTCommonStatusGuardSetOff)||a==nFTCommonStatusAppeal||fp->proc_interrupt==ftCommonJumpAerialProcInterrupt;}
static sb32 clan_thrown_update(GObj *g){ITStruct *ip=itGetStruct(g);ClanItem *s=CLAN(ip);if(s->mode<=0){s->mode=1;s->timer=s->type==2?50:28;if(s->type==2||s->type==3){if(ABSF(ip->physics.vel_air.x)<=ABSF(ip->physics.vel_air.y))ip->physics.vel_air.x=0;else ip->physics.vel_air.y=0;if(s->type==2){ip->is_thrown=FALSE;ip->attack_coll.angle=ip->physics.vel_air.y>0?270:ip->physics.vel_air.y<0?90:150;}}}
 itVisualsUpdateSpin(g);if(s->type==1||s->type==4){itMainApplyGravityClampTVel(ip,ITBOMBHEI_GRAVITY,ITBOMBHEI_TVEL);return FALSE;}
 if(s->refresh&&!--s->refresh)memset(ip->attack_coll.attack_records,0,sizeof(ip->attack_coll.attack_records));
 if(s->type==2){if(s->mode==1&&!--s->timer){s->mode=2;s->timer=30;}else if(s->mode==2){clan_scale(g,0.9375F);if(!--s->timer)clan_fall(g);}return FALSE;}
 if(s->mode==1){if(!--s->timer)clan_turn(g);}else if(s->mode==2){float *v=s->axis?&ip->physics.vel_air.y:&ip->physics.vel_air.x;*v+=s->accel;if(ABSF(*v)>ABSF(s->target)){*v=s->target;s->mode=3;s->timer=40;}}else if(s->mode==3){GObj *owner=ip->owner_gobj;if(sonic_live(owner,nGCCommonLinkIDFighter)){FTStruct *fp=ftGetStruct(owner);Vec3f p=DObjGetStruct(g)->translate.vec.f,q=DObjGetStruct(owner)->translate.vec.f;float dy=p.y-q.y;if(!fp->item_gobj&&!fp->catch_gobj&&clan_can_catch(fp)&&ABSF(p.x-q.x)<=280&&dy>=-100&&dy<=440){itMainSetFighterHold(g,owner);return FALSE;}}if(!--s->timer){clan_scale(g,0.5F);clan_fall(g);}}
 return FALSE;
}
static sb32 clan_thrown_map(GObj *g){if(!itMapTestAllCheckCollEnd(g))return FALSE;ITStruct *ip=itGetStruct(g);ClanItem *s=CLAN(ip);if(s->type==4){clan_bomb_explode(g);return FALSE;}if(s->type==3){if(s->mode<3)return clan_hit(g);clan_scale(g,-0.5F);clan_fall(g);return FALSE;}if(s->type==2&&s->mode==2){ip->physics.vel_air.x=ip->physics.vel_air.y=0;return FALSE;}return clan_destroy(g);}
static GObj *clan_make(GObj *g,int type){if(type<1||type>4||!main_files[63][7])return NULL;Vec3f p=DObjGetStruct(g)->translate.vec.f,v={0,0,0};ITDesc d=dItLinkBombItemDesc;d.p_file=&main_files[63][7];d.o_attributes=0x40+0x50*(type-1);d.transform_types=(DObjTransformTypes){0x1B,0,0};d.proc_update=clan_fall_update;d.proc_map=clan_fall_map;d.proc_hit=clan_hit;d.proc_shield=clan_shield;d.proc_hop=itMainCommonProcHop;d.proc_setoff=clan_hit;d.proc_reflector=clan_reflect;d.proc_damage=clan_damage;GObj *item=itManagerMakeItem(g,&d,&p,&v,ITEM_FLAG_PARENT_FIGHTER);if(!item)return NULL;ITStruct *ip=itGetStruct(item);memset(&ip->item_vars,0,sizeof(ip->item_vars));CLAN(ip)->type=type;itMainClearOwnerStats(item);ip->damage_coll.hitstatus=nGMHitStatusNormal;ip->attack_coll.attack_state=nGMAttackStateOff;ip->lifetime=780;int dmg[]={0,4,2,1,1},bkb[]={0,40,70,70,80},kbg[]={0,90,50,40,70};ip->attack_coll.damage=dmg[type];ip->attack_coll.knockback_base=bkb[type];ip->attack_coll.knockback_scale=kbg[type];ip->attack_coll.angle=type==2?150:type==3?68:ip->attack_coll.angle;DObj *root=DObjGetStruct(item);gcAddXObjForDObjFixed(root,0x2E,0);if(root->mobj)root->mobj->palette_id=type;return item;}
static void clan_install(void){clan_status[0]=(ITStatusDesc){NULL,clan_wait_map,NULL,NULL,NULL,NULL,NULL,clan_damage};clan_status[1]=(ITStatusDesc){clan_fall_update,clan_fall_map,NULL,NULL,NULL,NULL,NULL,clan_damage};clan_status[2]=(ITStatusDesc){clan_hold_update};clan_status[3]=(ITStatusDesc){clan_thrown_update,clan_thrown_map,clan_hit,clan_shield,itMainCommonProcHop,clan_hit,clan_reflect,clan_damage};clan_status[4]=clan_status[1];clan_status[5]=(ITStatusDesc){clan_bomb_update};}
