/* MewtwoSpecial.asm: Shadow Ball charge/recoil, directional Teleport, Disable. */
static FTStatusDesc mewtwo_status[64];
static wpSamusChargeShotAttributes mewtwo_levels[]={
 {130,70,2,90,10,0x1A,0x3C9,0x1C,1},{160,72,4,110,10,0x1A,0x3CA,0x1C,1},
 {200,74,6,130,10,0x1A,0x3CB,0x1B,1},{260,76,9,150,10,0x3C,0x3CC,0x1B,1},
 {330,78,12,170,10,0x3C,0x3CD,0x1B,1},{410,80,15,190,10,0x3C,0x3CE,0x19,1},
 {500,82,18,210,10,0x3C,0x3CF,0x19,1},{600,84,22,230,10,0xC1,0x3D0,0x19,2}};
static int mewtwo_timer[4];static float mewtwo_angle[4];
wpSamusChargeShotAttributes *port_remix_mewtwo_levels(GObj *g,wpSamusChargeShotAttributes *native){return wpGetStruct(g)->port_remix_origin==57?mewtwo_levels:native;}
int port_remix_mewtwo_ball_position(FTStruct *fp,Vec3f *p){if(!port_remix_enabled()||fp->fkind!=57)return 0;*p=(Vec3f){0,0,0};gmCollisionGetFighterPartsWorldPosition(fp->joints[36],p);return 1;}
void port_remix_mewtwo_ball_init(GObj *g){WPStruct *wp=wpGetStruct(g);if(wp->port_remix_origin==57){wp->lifetime=0;wp->remix_speed_scale=DObjGetStruct(g)->translate.vec.f.y;}}
static sb32 shadow_update(GObj *g){WPStruct *wp=wpGetStruct(g);int *released=&wp->weapon_vars.charge_shot.is_release;
 if(!*released){float size=mewtwo_levels[wp->weapon_vars.charge_shot.charge_size].gfx_size/30;DObjGetStruct(g)->scale.vec.f.x=DObjGetStruct(g)->scale.vec.f.y=size;if(!wp->weapon_vars.charge_shot.is_full_charge)return FALSE;wp->remix_speed_scale=DObjGetStruct(g)->translate.vec.f.y;wpSamusChargeShotLaunch(g);wp->attack_coll.attack_state=nGMAttackStateNew;wpProcessUpdateHitPositions(g);*released=1;wp->lifetime=1;return FALSE;}
 if(*released==1)DObjGetStruct(g)->translate.vec.f.y=wp->remix_speed_scale+100*sinf(0.314159265F*wp->lifetime);wp->lifetime++;return FALSE;
}
static sb32 shadow_hit(GObj *g){efManagerDamageFireMakeEffect(&DObjGetStruct(g)->translate.vec.f,wpGetStruct(g)->attack_coll.damage);func_800269C0_275C0(0x3C);return TRUE;}
static sb32 shadow_map(GObj *g){WPStruct *wp=wpGetStruct(g);if(wp->weapon_vars.charge_shot.is_release&&wpMapTestAllCheckCollEnd(g)){int full=wp->weapon_vars.charge_shot.charge_size==7;efManagerSparkleWhiteMultiExplodeMakeEffect(&DObjGetStruct(g)->translate.vec.f);efManagerQuakeMakeEffect(full);func_800269C0_275C0(full);return TRUE;}return FALSE;}
static sb32 shadow_hop(GObj *g){wpGetStruct(g)->weapon_vars.charge_shot.is_release=2;return wpSamusChargeShotProcHop(g);}
void port_remix_mewtwo_weapon_desc(int origin,WPDesc *d){if(origin==57&&d->kind==nWPKindChargeShot){d->p_weapon=&main_files[57][7];d->o_attributes=0;d->transform_types=(DObjTransformTypes){0x12,0x2E,0};d->proc_update=shadow_update;d->proc_map=shadow_map;d->proc_hit=d->proc_shield=d->proc_setoff=d->proc_absorb=shadow_hit;d->proc_hop=shadow_hop;}}
static void mewtwo_attach(GObj *g){FTStruct *fp=ftGetStruct(g);Vec3f pos;fp->proc_damage=ftSamusSpecialNProcDamage;fp->status_vars.samus.specialn.charge_int=20;ftSamusSpecialNGetChargeShotPosition(fp,&pos);fp->status_vars.samus.specialn.charge_gobj=wpSamusChargeShotMakeWeapon(g,&pos,fp->passive_vars.samus.charge_level,FALSE);}
static void mewtwo_shoot(GObj *g){FTStruct *fp=ftGetStruct(g);ftMainSetStatus(g,fp->ga==nMPKineticsAir?228:224,0,1,0x800);fp->motion_vars.flags.flag0=0;fp->proc_damage=ftSamusSpecialNProcDamage;}
static void mewtwo_n_start(GObj *g){if(g->anim_frame>0)return;FTStruct *fp=ftGetStruct(g);if(fp->status_vars.samus.specialn.is_release){mewtwo_attach(g);mewtwo_shoot(g);}else{ftMainSetStatus(g,fp->ga==nMPKineticsAir?226:223,0,1,2);mewtwo_attach(g);}}
static void mewtwo_ng(GObj *g){ftManagerSetupFilesAllKind(nFTKindSamus);ftSamusSpecialNStartSetStatus(g);}
static void mewtwo_na(GObj *g){ftManagerSetupFilesAllKind(nFTKindSamus);ftSamusSpecialAirNStartSetStatus(g);FTStruct *fp=ftGetStruct(g);fp->status_vars.samus.specialn.is_release=fp->passive_vars.samus.charge_level==7;}
static void mewtwo_charge_update(GObj *g){FTStruct *fp=ftGetStruct(g);ftSamusSpecialNSetChargeShotPosition(fp);if(--fp->status_vars.samus.specialn.charge_int)return;fp->status_vars.samus.specialn.charge_int=20;if(fp->passive_vars.samus.charge_level>=7)return;if(++fp->passive_vars.samus.charge_level==7){ftSamusSpecialNDestroyChargeShot(fp);mpCommonSetFighterWaitOrFall(g);}else if(fp->status_vars.samus.specialn.charge_gobj)wpGetStruct(fp->status_vars.samus.specialn.charge_gobj)->weapon_vars.charge_shot.charge_size=fp->passive_vars.samus.charge_level;}
static void mewtwo_charge_interrupt(GObj *g){FTStruct *fp=ftGetStruct(g);int tap=fp->input.pl.button_tap;if(tap&(fp->input.button_mask_a|fp->input.button_mask_b)){mewtwo_shoot(g);return;}if(fp->ga==nMPKineticsGround){int s=ftCommonEscapeGetStatus(fp);if(s!=-1){ftSamusSpecialNDestroyChargeShot(fp);ftCommonEscapeSetStatus(g,s,0);return;}}if(tap&fp->input.button_mask_z){ftSamusSpecialNDestroyChargeShot(fp);mpCommonSetFighterWaitOrFall(g);}}
static void mewtwo_shoot_update(GObj *g){FTStruct *fp=ftGetStruct(g);int fire=fp->motion_vars.flags.flag0,level=fp->passive_vars.samus.charge_level,recoil=fp->passive_vars.samus.charge_recoil,air=fp->ga==nMPKineticsAir;float y=fp->physics.vel_air.y;ftSamusSpecialNSetChargeShotPosition(fp);ftSamusSpecialNEndProcUpdate(g);if(fire&&air){fp->physics.vel_air.x=-(12+7*level)*fp->lr;float lift=level+21-recoil*5;fp->physics.vel_air.y=y>lift?y:lift;}}
static int mewtwo_n_pair(int a,int air){switch(a){case 222:case 225:return air?225:222;case 223:case 226:return air?226:223;default:return air?228:224;}}
static void mewtwo_n_air(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterAir(fp);ftMainSetStatus(g,mewtwo_n_pair(fp->status_id,1),g->anim_frame,1,0x802);fp->proc_damage=ftSamusSpecialNProcDamage;}
static void mewtwo_n_ground(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterGround(fp);ftMainSetStatus(g,mewtwo_n_pair(fp->status_id,0),g->anim_frame,1,0x802);fp->proc_damage=ftSamusSpecialNProcDamage;}
static void mewtwo_n_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,mewtwo_n_air);else mpCommonProcFighterLanding(g,mewtwo_n_ground);}
static void mewtwo_h_enter(GObj *g,int air){FTStruct *fp=ftGetStruct(g);ftMainSetStatus(g,air?237:234,0,1,0);ftMainPlayAnimEventsAll(g);marth_clear_flags(fp);if(air){fp->physics.vel_air.x*=0.5F;fp->physics.vel_air.y*=0.5F;fp->is_fastfall=FALSE;}else fp->physics.vel_ground.x*=0.5F;}
static void mewtwo_hg(GObj *g){mewtwo_h_enter(g,0);}static void mewtwo_ha(GObj *g){mewtwo_h_enter(g,1);}
static void mewtwo_move_physics(GObj *g){FTStruct *fp=ftGetStruct(g);float a=mewtwo_angle[fp->player];fp->physics.vel_air.x=128*cosf(a)*fp->lr;if(fp->ga==nMPKineticsGround)fp->physics.vel_ground.x=128*cosf(a);else fp->physics.vel_air.y=128*sinf(a);}
static void mewtwo_hide(GObj *g){FTStruct *fp=ftGetStruct(g);fp->is_invisible=TRUE;ftParamSetHitStatusAll(g,nGMHitStatusIntangible);}
static void mewtwo_move_enter(GObj *g){FTStruct *fp=ftGetStruct(g);int x=fp->input.pl.stick_range.x,y=fp->input.pl.stick_range.y,ground=fp->ga==nMPKineticsGround,dead=x*x+y*y<121;if(ABSF(x)>=11)fp->lr=x>0?1:-1;if(dead||!ground||y||!x)mpCommonSetFighterAir(fp);mewtwo_angle[fp->player]=dead?1.570796327F:syUtilsArcTan2(y,x*fp->lr);ftMainSetStatus(g,fp->ga==nMPKineticsGround?235:238,0,1,0);fp->jumps_used=fp->attr->jumps_max;mewtwo_timer[fp->player]=12;mewtwo_move_physics(g);mewtwo_hide(g);if(ground)fp->coll_data.ignore_line_id=fp->coll_data.floor_line_id;}
static void mewtwo_h_begin_update(GObj *g){if(g->anim_frame<=0)mewtwo_move_enter(g);}
static void mewtwo_h_move_update(GObj *g){FTStruct *fp=ftGetStruct(g);if(--mewtwo_timer[fp->player])return;int air=fp->ga==nMPKineticsAir;ftMainSetStatus(g,air?239:236,0,1,0);ftMainPlayAnimEventsAll(g);if(air){fp->physics.vel_air.x*=0.25F;fp->physics.vel_air.y*=0.25F;}else fp->physics.vel_ground.x*=0.5F;}
static void mewtwo_h_end_update(GObj *g){FTStruct *fp=ftGetStruct(g);fp->is_invisible=fp->motion_vars.flags.flag2!=0;if(g->anim_frame<=0){if(fp->ga==nMPKineticsAir)ftCommonFallSpecialSetStatus(g,0.9375F,FALSE,TRUE,FALSE,1.23076928F,FALSE);else ftCommonWaitSetStatus(g);}}
static void mewtwo_h_air(GObj *g){FTStruct *fp=ftGetStruct(g);int move=fp->status_id==235;mpCommonSetFighterAir(fp);ftMainSetStatus(g,move?238:237,g->anim_frame,1,0);if(move)mewtwo_hide(g);}
static void mewtwo_h_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int move=fp->status_id==238;mpCommonSetFighterGround(fp);ftMainSetStatus(g,move?235:234,g->anim_frame,1,0);if(move)mewtwo_hide(g);}
static void mewtwo_h_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,mewtwo_h_air);else if(fp->status_id==238)mpCommonProcFighterCliff(g,mewtwo_h_ground);else mpCommonProcFighterLanding(g,mewtwo_h_ground);}
static void mewtwo_h_end_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround){mpCommonSetFighterFallOnEdgeBreak(g);return;}if(fp->physics.vel_air.y>=0)mpCommonCheckFighterProject(g);else if(mpCommonCheckFighterPassCliff(g,ftSamusSpecialHiProcPass)){if(fp->coll_data.mask_stat&MAP_FLAG_CLIFF_MASK)ftCommonCliffCatchSetStatus(g);else ftCommonLandingFallSpecialSetStatus(g,FALSE,1.23076928F);}}
static void mewtwo_dg(GObj *g){ftMainSetStatus(g,229,0,1,0);ftMainPlayAnimEventsAll(g);}static void mewtwo_da(GObj *g){ftMainSetStatus(g,230,0,1,0);ftMainPlayAnimEventsAll(g);ftGetStruct(g)->physics.vel_air.y=0;}
static void mewtwo_d_air(GObj *g){mpCommonSetFighterAir(ftGetStruct(g));ftMainSetStatus(g,230,g->anim_frame,1,0);}
static void mewtwo_d_ground(GObj *g){mpCommonSetFighterGround(ftGetStruct(g));ftMainSetStatus(g,229,g->anim_frame,1,0);}
static void mewtwo_d_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,mewtwo_d_air);else mpCommonProcFighterLanding(g,mewtwo_d_ground);}
/* Disable only stuns a grounded opponent facing the incoming hit. */
int port_remix_disable_damage(GObj *g){FTStruct *fp=ftGetStruct(g);if(!port_remix_enabled()||fp->damage_element!=8||fp->ga!=nMPKineticsGround||fp->status_id==nFTCommonStatusFuraFura||fp->damage_lr!=fp->lr)return 0;ftCommonFuraFuraSetStatus(g);return 1;}
static void mewtwo_install(FighterDescriptor *d){memcpy(mewtwo_status,safe_statuses,sizeof(mewtwo_status));int actions[]={222,223,224,225,226,228,229,230,234,235,236,237,238,239};int motions[]={197,198,199,200,201,202,203,204,208,-1,209,210,-1,211};for(int i=0;i<14;i++){int a=actions[i],air=a==225||a==226||a==228||a==230||a>=237;FTStatusDesc *s=mewtwo_status+a-220;s->mflags.motion_id=motions[i];s->mflags.attack_id=a<229?18:a<234?30:17;s->sflags.attack_id=s->mflags.attack_id;s->sflags.ga=air;s->proc_update=a==222||a==225?mewtwo_n_start:a==223||a==226?mewtwo_charge_update:a==224||a==228?mewtwo_shoot_update:a==229?ftAnimEndSetWait:a==230?ftAnimEndSetFall:a==234||a==237?mewtwo_h_begin_update:a==235||a==238?mewtwo_h_move_update:mewtwo_h_end_update;s->proc_interrupt=a==222||a==225?ftSamusSpecialNStartProcInterrupt:a==223||a==226?mewtwo_charge_interrupt:NULL;s->proc_physics=a==235||a==238?mewtwo_move_physics:air?(a==225?ftPhysicsApplyAirVelDrift:ftPhysicsApplyAirVelFriction):ftPhysicsApplyGroundVelFriction;s->proc_map=a<229?mewtwo_n_map:a<234?mewtwo_d_map:a==236||a==239?mewtwo_h_end_map:mewtwo_h_map;}
 d->special_descs=mewtwo_status;d->special_handler[0]=mewtwo_ng;d->special_handler[1]=mewtwo_hg;d->special_handler[2]=mewtwo_dg;d->special_handler[3]=mewtwo_na;d->special_handler[4]=mewtwo_ha;d->special_handler[5]=mewtwo_da;
}
