/* BanjoSpecial.asm: Egg Firing, Shock Spring Jump/Beak Bomb, Rat-a-tat Rap/Bill Drill. */
static FTStatusDesc banjo_status[64];
static struct {int ground,buffer,recoil;} banjo_state[4];
#define BANJO(fp) (&banjo_state[(fp)->player])
static void banjo_enter(GObj *g,int a,int flags){remix_copy_set(g,68,a,0,1,flags);ftMainPlayAnimEventsAll(g);}
static sb32 banjo_egg_hit(GObj *g){efManagerDustExpandSmallMakeEffect(&DObjGetStruct(g)->translate.vec.f,1);return TRUE;}
static sb32 banjo_egg_update(GObj *g){WPStruct *wp=wpGetStruct(g);if(wpMainDecLifeCheckExpire(wp))return banjo_egg_hit(g);int back=wp->weapon_vars.fireball.index;wpMainApplyGravityClampTVel(wp,back?1.2F:0.1F,250);DObjGetStruct(g)->rotate.vec.f.x+=back?0.1F:0.15F;return FALSE;}
static sb32 banjo_egg_map(GObj *g){if(!wpGetStruct(g)->weapon_vars.fireball.index)return itLGunWeaponAmmoProcMap(g);wpMapTestAll(g);Vec3f pos;if(wpMapCheckAllRebound(g,MAP_FLAG_MAIN_MASK,0.9F,&pos)){wpMainVelSetModelPitch(g);efManagerFireGrindMakeEffect(&DObjGetStruct(g)->translate.vec.f);}return FALSE;}
static void banjo_egg(GObj *g,int back){FTStruct *fp=ftGetStruct(g);Vec3f p={back?0:-40,fp->fkind==8?-160:0,0};gmCollisionGetFighterPartsWorldPosition(fp->joints[21],&p);p.z=0;WPDesc d={0};d.kind=nWPKindFireball;d.p_weapon=&main_files[68][8];d.o_attributes=0;d.transform_types=(DObjTransformTypes){0x12,0x47,0};d.proc_update=banjo_egg_update;d.proc_map=banjo_egg_map;d.proc_hit=d.proc_shield=d.proc_setoff=d.proc_absorb=banjo_egg_hit;d.proc_hop=wpBossBulletProcHop;d.proc_reflector=wpSamusBombProcReflector;GObj *w=wpManagerMakeWeapon(g,&d,&p,WEAPON_FLAG_PARENT_FIGHTER);if(w){WPStruct *wp=wpGetStruct(w);wp->weapon_vars.fireball.index=back;wp->lifetime=back?120:30;wp->attack_coll.element=0;wp->attack_coll.fgm_id=0x28;float angle=back?128:0,speed=back?28:90;wp->physics.vel_air=(Vec3f){cosf(angle)*speed*fp->lr,sinf(angle)*speed,0};wpMainVelSetModelPitch(w);}}
static void banjo_n(GObj *g){FTStruct *fp=ftGetStruct(g);marth_clear_flags(fp);banjo_enter(g,fp->ga==nMPKineticsAir?228:225,0);}
static void banjo_n_update(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,68);if(a==225||a==228){if(g->anim_frame<=0){int back=fp->input.pl.stick_range.x*fp->lr<=-6;banjo_enter(g,a+1+back,0);marth_clear_flags(fp);}}else{if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=0;banjo_egg(g,a==227||a==230);}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}}
static void banjo_n_physics(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround)ftPhysicsApplyGroundVelFriction(g);else if(fp->motion_vars.flags.flag1)ftPhysicsApplyAirVelDrift(g);else ftPhysicsApplyAirVelFriction(g);}
static void banjo_n_air(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,68)+3;mpCommonSetFighterAir(fp);remix_copy_set(g,68,a,g->anim_frame,1,2);ftPhysicsClampAirVelXMax(fp);}
static void banjo_n_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,68)-3;mpCommonSetFighterGround(fp);remix_copy_set(g,68,a,g->anim_frame,1,2);}
static void banjo_n_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,banjo_n_air);else mpCommonProcFighterLanding(g,banjo_n_ground);}
static void banjo_up(GObj *g){FTStruct *fp=ftGetStruct(g);BANJO(fp)->ground=fp->ga==nMPKineticsGround;BANJO(fp)->buffer=BANJO(fp)->recoil=0;mpCommonSetFighterAir(fp);marth_clear_flags(fp);banjo_enter(g,236,0);}
static void banjo_specialfall(GObj *g){ftCommonFallSpecialSetStatus(g,1,FALSE,TRUE,FALSE,ftGetStruct(g)->status_id==236||ftGetStruct(g)->status_id==240?2:1,FALSE);}
static void banjo_up_update(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(a==236){BANJO(fp)->buffer|=fp->input.pl.button_tap&fp->input.button_mask_b;if(g->anim_frame>10&&BANJO(fp)->buffer){marth_clear_flags(fp);banjo_enter(g,237,3);ftFoxSpecialHiHoldInitStatusVars(g);return;}}else if(a==237){if(g->anim_frame==39){banjo_enter(g,238,0);fp->physics.vel_air.x*=0.5F;}return;}else if(a==239){ftAnimEndSetFall(g);return;}else if(a==240&&fp->motion_vars.flags.flag0)DObjGetStruct(g)->rotate.vec.f.x*=0.90625F;if(g->anim_frame<=0)banjo_specialfall(g);}
void port_remix_banjo_contact(FTStruct *fp,int type){if(port_remix_enabled()&&fp->fkind==68&&fp->status_id==237)BANJO(fp)->recoil=1;}
static void banjo_up_interrupt(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->status_id==237){if(fp->motion_vars.flags.flag1==2)wolf_up_turn(g);if(BANJO(fp)->recoil||fp->motion_vars.flags.flag0){BANJO(fp)->recoil=0;banjo_enter(g,239,3);fp->motion_vars.flags.flag1=0;fp->physics.vel_air=(Vec3f){-20*fp->lr,48,0};}}else if(fp->status_id==239&&!fp->motion_vars.flags.flag0){fp->physics.vel_air.x*=0.96875F;fp->physics.vel_air.y+=1.25F;}}
static void banjo_up_physics(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id,phase=fp->motion_vars.flags.flag2;if(a==239||a==240){if(a==240&&phase){fp->motion_vars.flags.flag2=0;fp->physics.vel_air.x=-15*fp->lr;}if(fp->motion_vars.flags.flag0)ftPhysicsApplyAirVelDrift(g);else ftPhysicsApplyAirVelFriction(g);return;}ftPhysicsApplyAirVelFriction(g);if(a==236){if(!phase)fp->physics.vel_air.x=fp->physics.vel_air.y=0;else if(phase==1){fp->physics.vel_air.y=BANJO(fp)->ground?101:90;fp->motion_vars.flags.flag2=2;fp->jumps_used=fp->attr->jumps_max;}ftPhysicsClampAirVelXStickDefault(fp,fp->attr);}else if(a==237){if(!phase)fp->physics.vel_air.x=fp->physics.vel_air.y=0;else if(phase==1){fp->physics.vel_air.x=-20*fp->lr;fp->physics.vel_air.y=fp->attr->gravity;}else if(phase==2){fp->physics.vel_air.x=80*fp->lr;fp->physics.vel_air.y=fp->attr->gravity;fp->motion_vars.flags.flag2=3;}else if(phase==3)fp->physics.vel_air.y+=fp->attr->gravity;}}
static void banjo_up_map(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(a==239){mpCommonProcFighterCliffWaitOrLanding(g);return;}if(fp->physics.vel_air.y>=0)mpCommonCheckFighterProject(g);else if(mpCommonCheckFighterPassCliff(g,ftSamusSpecialHiProcPass)){if(fp->coll_data.mask_stat&MAP_FLAG_CLIFF_MASK)ftCommonCliffCatchSetStatus(g);else ftCommonLandingFallSpecialSetStatus(g,FALSE,a==236?2:1);return;}if(a==237&&fp->motion_vars.flags.flag2==3&&(fp->coll_data.mask_curr&(fp->lr>0?MAP_FLAG_LWALL:MAP_FLAG_RWALL))){Vec3f angle=fp->lr>0?fp->coll_data.lwall_angle:fp->coll_data.rwall_angle;banjo_enter(g,240,0);marth_clear_flags(fp);fp->physics.vel_air=(Vec3f){0,5,0};DObjGetStruct(g)->rotate.vec.f.x=angle.y;efManagerQuakeMakeEffect(2);efManagerImpactWaveMakeEffect(&DObjGetStruct(g)->translate.vec.f,SYVECTOR_AXIS_Z,syUtilsArcTan2(angle.y,-angle.x));}}
static void banjo_down(GObj *g){FTStruct *fp=ftGetStruct(g);int air=fp->ga==nMPKineticsAir;banjo_enter(g,air?231:233,air?8:0);marth_clear_flags(fp);fp->motion_vars.flags.flag2=1;if(air)fp->is_fastfall=FALSE;}
static void banjo_d_update(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(a==231){if(g->anim_frame<=0){banjo_enter(g,235,1);marth_clear_flags(fp);}}else if(a==233||a==232)ftAnimEndSetWait(g);else if(a==234)ftAnimEndSetFall(g);}
static void banjo_d_move(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->motion_vars.flags.flag2==1)fp->physics.vel_air.y*=0.75F;else fp->physics.vel_air.x*=0.875F;}
static void banjo_d_physics(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->motion_vars.flags.flag1)ftPhysicsApplyAirVelFriction(g);else ftPhysicsApplyAirVelDrift(g);fp->physics.vel_air.y=fp->status_id==235||fp->motion_vars.flags.flag2==2?-110:12;}
static void banjo_d_land(GObj *g){mpCommonSetFighterGround(ftGetStruct(g));banjo_enter(g,232,0);}
static void banjo_d_ground_air(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterAir(fp);if(fp->motion_vars.flags.flag1==1)banjo_enter(g,234,4);}
static void banjo_d_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->status_id==233){mpCommonProcFighterOnFloor(g,banjo_d_ground_air);return;}if(fp->status_id==232){mpCommonProcFighterOnFloor(g,ftCommonFallSetStatus);return;}if(fp->status_id==234){mpCommonProcFighterCliffWaitOrLanding(g);return;}if(fp->motion_vars.flags.flag2==2||fp->status_id==235)mpCommonProcFighterCliff(g,banjo_d_land);else mpCommonProcFighterCliffWaitOrLanding(g);}
static void banjo_install(FighterDescriptor *d){memcpy(banjo_status,safe_statuses,sizeof(banjo_status));for(int a=225;a<=240;a++){FTStatusDesc *s=banjo_status+a-220;int n=a<=230,down=a>=231&&a<=235,air=n?a>=228:down?(a==231||a==234||a==235):1;s->mflags.motion_id=a>=236?a-22:a-25;s->mflags.attack_id=s->sflags.attack_id=n?18:down?30:17;s->sflags.ga=air;s->proc_update=n?banjo_n_update:down?banjo_d_update:banjo_up_update;s->proc_interrupt=a==231||a==235?banjo_d_move:a==237||a==239?banjo_up_interrupt:NULL;s->proc_physics=n?banjo_n_physics:down?(a==231||a==235?banjo_d_physics:a==233?ftPhysicsApplyGroundVelTransN:ftPhysicsApplyGroundVelFriction):banjo_up_physics;s->proc_map=n?banjo_n_map:down?banjo_d_map:banjo_up_map;}d->special_descs=banjo_status;d->special_handler[0]=d->special_handler[3]=banjo_n;d->special_handler[1]=d->special_handler[4]=banjo_up;d->special_handler[2]=d->special_handler[5]=banjo_down;}
