/* SonicSpecial.asm: homing attack, reusable spring, charged Spin Dash. */
static FTStatusDesc sonic_status[64];
static struct {GObj *target,*spring;int target_link,timer,charge,up_used,up_started,ground_start,spring_created,contact;float angle,speed;} sonic_state[4];
#define SONIC_STATE(fp) (&sonic_state[(fp)->player])
static int sonic_live(GObj *obj,int link){if(!obj)return FALSE;for(GObj *g=gGCCommonLinks[link];g;g=g->link_next)if(g==obj)return TRUE;return FALSE;}
void port_remix_sonic_tick(GObj *g){FTStruct *fp=ftGetStruct(g);if(port_remix_enabled()&&fp->fkind==59&&(fp->ga==nMPKineticsGround||fp->status_id<7||fp->status_id>=nFTCommonStatusDamageHi1&&fp->status_id<=nFTCommonStatusDamageFlyRoll))SONIC_STATE(fp)->up_used=0;}
int port_remix_sonic_special_block(GObj *g){FTStruct *fp=ftGetStruct(g);return port_remix_enabled()&&fp->fkind==59&&SONIC_STATE(fp)->up_used;}
void port_remix_sonic_contact(FTStruct *fp,int type){if(port_remix_enabled()&&remix_copy_kind(fp,59)&&(remix_copy_current(fp,59)==254||remix_copy_current(fp,59)==255)&&(type==nGMHitTypeDamage||type==nGMHitTypeShield||type==nGMHitTypeAttack))SONIC_STATE(fp)->contact=1;}
static void sonic_enter(GObj *g,int a){remix_copy_set(g,59,a,0,1,0);ftMainPlayAnimEventsAll(g);}
static void sonic_end_n(GObj *g){FTStruct *fp=ftGetStruct(g);sonic_enter(g,fp->ga==nMPKineticsGround?256:257);if(fp->ga==nMPKineticsGround)fp->physics.vel_ground.x*=0.5F;else{fp->physics.vel_air.x*=0.5F;fp->physics.vel_air.y*=0.5F;}}
static void sonic_recoil(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterAir(fp);sonic_enter(g,259);fp->physics.vel_air.x=-20*fp->lr;fp->physics.vel_air.y=80;}
static void sonic_bounce(GObj *g){FTStruct *fp=ftGetStruct(g);sonic_enter(g,260);fp->physics.vel_air.x*=0.25F;fp->physics.vel_air.y=60;}
static void sonic_n(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterAir(fp);marth_clear_flags(fp);sonic_enter(g,253);fp->is_fastfall=FALSE;fp->physics.vel_air.x=0;fp->physics.vel_air.y=12;SONIC_STATE(fp)->target=NULL;SONIC_STATE(fp)->contact=0;}
static void sonic_target(GObj *g){FTStruct *fp=ftGetStruct(g);__typeof__(sonic_state[0]) *s=SONIC_STATE(fp);Vec3f p=DObjGetStruct(g)->translate.vec.f;float best=2209;s->target=NULL;
 int links[]={nGCCommonLinkIDFighter,nGCCommonLinkIDItem};for(int k=0;k<2&&!s->target;k++)for(GObj *t=gGCCommonLinks[links[k]];t;t=t->link_next){if(t==g)continue;if(!k){FTStruct *tf=ftGetStruct(t);if(tf->status_id<7||(gSCManagerBattleState->is_team_battle&&!gSCManagerBattleState->is_team_attack&&fp->team==tf->team))continue;}else if(itGetStruct(t)->damage_coll.hitstatus!=nGMHitStatusNormal)continue;Vec3f q=DObjGetStruct(t)->translate.vec.f;float x=(q.x-p.x)*fp->lr,y=q.y-p.y;if(x<0||x>2208||ABSF(y)>1000+x*0.5F||x>=best)continue;best=x;s->target=t;s->target_link=links[k];}
}
static void sonic_n_begin_update(GObj *g){FTStruct *fp=ftGetStruct(g);int flag=fp->motion_vars.flags.flag0;if(!flag||flag==1&&(fp->input.pl.button_hold&fp->input.button_mask_b))return;sonic_target(g);__typeof__(sonic_state[0]) *s=SONIC_STATE(fp);s->angle=-0.366519F;s->timer=12;s->speed=110;if(s->target){Vec3f p=DObjGetStruct(g)->translate.vec.f,q=DObjGetStruct(s->target)->translate.vec.f;s->angle=syUtilsArcTan2(q.y-p.y,(q.x-p.x)*fp->lr);if(s->angle>0.610865F)s->angle=0.610865F;if(s->angle<-0.610865F)s->angle=-0.610865F;s->timer=20;s->speed=130;}sonic_enter(g,s->target?255:254);}
static void sonic_n_move_update(GObj *g){FTStruct *fp=ftGetStruct(g);if(SONIC_STATE(fp)->contact){sonic_recoil(g);return;}if(!--SONIC_STATE(fp)->timer)sonic_end_n(g);}
static void sonic_n_physics(GObj *g){FTStruct *fp=ftGetStruct(g);__typeof__(sonic_state[0]) *s=SONIC_STATE(fp);if(sonic_live(s->target,s->target_link)){Vec3f p=DObjGetStruct(g)->translate.vec.f,q=DObjGetStruct(s->target)->translate.vec.f;float diff=syUtilsArcTan2(q.y-p.y,(q.x-p.x)*fp->lr)-s->angle;while(diff<-3.141592654F)diff+=6.283185307F;while(diff>3.141592654F)diff-=6.283185307F;if(diff>0.139626F)diff=0.139626F;if(diff<-0.139626F)diff=-0.139626F;s->angle+=diff;}fp->joints[nFTPartsJointTopN]->rotate.vec.f.z=s->angle*fp->lr;fp->physics.vel_air.x=s->speed*cosf(s->angle)*fp->lr;fp->physics.vel_air.y=s->speed*sinf(s->angle);}
static void sonic_n_begin_map(GObj *g){mpCommonCheckFighterLanding(g);}static void sonic_n_move_map(GObj *g){mpCommonProcFighterLanding(g,sonic_bounce);}
static void sonic_n_air(GObj *g){FTStruct *fp=ftGetStruct(g);int recoil=remix_copy_current(fp,59)==258;mpCommonSetFighterAir(fp);remix_copy_set(g,59,recoil?259:257,g->anim_frame,1,0);}
static void sonic_n_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int recoil=remix_copy_current(fp,59)==259;mpCommonSetFighterGround(fp);remix_copy_set(g,59,recoil?258:256,g->anim_frame,1,0);}
static void sonic_n_end_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,sonic_n_air);else mpCommonProcFighterLanding(g,sonic_n_ground);}
static void sonic_spring_coil(GObj *g,int coil){MObj *m=DObjGetStruct(g)->mobj;if(m){m->texture_id_curr=coil;m->palette_id=coil;}}
static sb32 sonic_spring_update(GObj *g){WPStruct *wp=wpGetStruct(g);if(wpMainDecLifeCheckExpire(wp)){efManagerDustExpandSmallMakeEffect(&DObjGetStruct(g)->translate.vec.f,1);return TRUE;}if(wp->lifetime>=236)return FALSE;wpMainApplyGravityClampTVel(wp,3,100);if(wp->ga==nMPKineticsAir){wp->attack_coll.interact_mask=1;DObjGetStruct(g)->rotate.vec.f.z+=0.1875F;return FALSE;}
 wp->attack_coll.interact_mask=0;memset(wp->attack_coll.attack_records,0,sizeof(wp->attack_coll.attack_records));DObjGetStruct(g)->rotate.vec.f.z=0;MObj *m=DObjGetStruct(g)->mobj;if(m&&(m->texture_id_curr&1)){sonic_spring_coil(g,0);return FALSE;}Vec3f p=DObjGetStruct(g)->translate.vec.f;
 for(GObj *t=gGCCommonLinks[nGCCommonLinkIDFighter];t;t=t->link_next){FTStruct *fp=ftGetStruct(t);Vec3f q=DObjGetStruct(t)->translate.vec.f;if(fp->ga!=nMPKineticsAir||q.z||fp->physics.vel_air.y>=0||ABSF(q.x-p.x)>wp->coll_data.map_coll.width||q.y<p.y||q.y>p.y+wp->coll_data.map_coll.top||fp->status_id==nFTKirbyStatusSpecialNCatch)continue;
 DObjGetStruct(t)->translate.vec.f.y=p.y;sonic_spring_coil(g,1);int a=fp->status_id;if(a>=nFTCommonStatusJumpF&&a<=nFTCommonStatusPass||a>=nFTCommonStatusDamageFall&&a<=nFTCommonStatusFallSpecial||fp->fkind==59&&a==228){ftMainSetStatus(t,nFTCommonStatusJumpF,0,1,0);ftMainPlayAnimEventsAll(t);}else efManagerDustHeavyDoubleMakeEffect(&DObjGetStruct(t)->translate.vec.f,1,1);
 fp->physics.vel_air.y=130;fp->physics.vel_damage_air.y=0;fp->is_fastfall=FALSE;if(fp->fkind==59)SONIC_STATE(fp)->up_used=0;func_800269C0_275C0(0x3D7);
 }return FALSE;
}
static GObj *sonic_make_spring(GObj *g){FTStruct *fp=ftGetStruct(g);Vec3f p={0,0,0};gmCollisionGetFighterPartsWorldPosition(fp->joints[4],&p);p.y-=228;p.z=0;WPDesc d={0};d.kind=nWPKindSamusBomb;d.p_weapon=&main_files[59][5];d.transform_types=(DObjTransformTypes){0x12,0x47,0};d.proc_update=sonic_spring_update;d.proc_map=d.proc_hit=wpSamusBombProcMap;d.proc_setoff=wpFoxBlasterProcReflector;GObj *w=wpManagerMakeWeapon(g,&d,&p,WEAPON_FLAG_PARENT_FIGHTER);if(!w)return NULL;WPStruct *wp=wpGetStruct(w);wp->lifetime=240;wp->attack_coll.interact_mask=0;wp->physics.vel_air=(Vec3f){0,0,0};sonic_spring_coil(w,1);if(SONIC_STATE(fp)->ground_start&&fp->coll_data.floor_line_id>=0){wp->ga=nMPKineticsGround;wp->coll_data.floor_line_id=fp->coll_data.floor_line_id;}return w;}
static void sonic_up(GObj *g){FTStruct *fp=ftGetStruct(g);__typeof__(sonic_state[0]) *s=SONIC_STATE(fp);s->ground_start=fp->ga==nMPKineticsGround;if(s->ground_start){mpCommonSetFighterAir(fp);DObjGetStruct(g)->translate.vec.f.y+=144;}s->up_started=0;s->spring_created=0;s->spring=NULL;fp->is_fastfall=FALSE;fp->physics.vel_air.x=fp->physics.vel_air.y=0;marth_clear_flags(fp);sonic_enter(g,228);}
static void sonic_up_update(GObj *g){FTStruct *fp=ftGetStruct(g);__typeof__(sonic_state[0]) *s=SONIC_STATE(fp);if(!s->spring_created){s->spring=sonic_make_spring(g);s->spring_created=1;}if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=0;if(sonic_live(s->spring,nGCCommonLinkIDWeapon))sonic_spring_coil(s->spring,0);fp->physics.vel_air.y=129;s->up_started=s->up_used=1;if(!s->ground_start)fp->jumps_used=fp->attr->jumps_max;}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}
static void sonic_up_physics(GObj *g){if(SONIC_STATE(ftGetStruct(g))->up_started)ftPhysicsApplyAirVelDrift(g);}
static void sonic_up_interrupt(GObj *g){if(ftGetStruct(g)->motion_vars.flags.flag1&&!ftCommonAttackAirCheckInterruptCommon(g))ftCommonJumpAerialCheckInterruptCommon(g);}
static void sonic_d_enter(GObj *g,int air){FTStruct *fp=ftGetStruct(g);marth_clear_flags(fp);sonic_enter(g,air?249:246);SONIC_STATE(fp)->charge=0;if(air){fp->physics.vel_air.y*=0.3125F;fp->is_fastfall=FALSE;}else fp->physics.vel_ground.x*=0.5F;}
static void sonic_dg(GObj *g){sonic_d_enter(g,0);}static void sonic_da(GObj *g){sonic_d_enter(g,1);}
static void sonic_d_move(GObj *g){FTStruct *fp=ftGetStruct(g);sonic_enter(g,247);fp->physics.vel_ground.x=46+SONIC_STATE(fp)->charge*4;fp->physics.vel_air.x=fp->physics.vel_ground.x*fp->lr;}
static void sonic_d_charge_update(GObj *g){FTStruct *fp=ftGetStruct(g);int *charge=&SONIC_STATE(fp)->charge,air=fp->ga==nMPKineticsAir;if(fp->input.pl.button_tap&(fp->input.button_mask_a|fp->input.button_mask_b)){*charge+=3;func_800269C0_275C0(0x3D8);}*charge+=fp->motion_vars.flags.flag1;fp->motion_vars.flags.flag1=0;int max=air?18:24;if(*charge>max)*charge=max;int flag=fp->motion_vars.flags.flag0;if(!flag||flag==1&&(fp->input.pl.stick_range.y<=-40||fp->input.pl.button_hold&fp->input.button_mask_b))return;if(air)sonic_enter(g,252);else sonic_d_move(g);}
static void sonic_d_charge_air(GObj *g){mpCommonSetFighterAir(ftGetStruct(g));ftMainSetStatus(g,249,g->anim_frame,1,0);}
static void sonic_d_charge_ground(GObj *g){mpCommonSetFighterGround(ftGetStruct(g));ftMainSetStatus(g,246,g->anim_frame,1,0);}
static void sonic_d_charge_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,sonic_d_charge_air);else mpCommonProcFighterLanding(g,sonic_d_charge_ground);}
static void sonic_spin_anim(GObj *g,float speed){FTStruct *fp=ftGetStruct(g);DObj *top=DObjGetStruct(g);if(top->anim_speed==1)top->anim_speed=1.000000119F;fp->joints[4]->anim_speed=fp->joints[5]->anim_speed=(speed+20)*0.0098876953125F;}
static void sonic_d_move_update(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround){fp->physics.vel_ground.x-=3.5F*sinf(ftKirbySpecialLwGetGroundAxisYaw(fp))*fp->lr;sonic_spin_anim(g,fp->physics.vel_ground.x);if(fp->physics.vel_ground.x<=15){sonic_enter(g,248);return;}if(ftCommonKneeBendGetInputTypeCommon(fp)){mpCommonSetFighterAir(fp);sonic_enter(g,251);fp->physics.vel_air.y=62;efManagerDustHeavyDoubleMakeEffect(&DObjGetStruct(g)->translate.vec.f,1,1);}}else{sonic_spin_anim(g,sqrtf(SQUARE(fp->physics.vel_air.x)+SQUARE(fp->physics.vel_air.y)));ftAnimEndSetFall(g);}}
static void sonic_d_interrupt(GObj *g){if(ftGetStruct(g)->motion_vars.flags.flag2)ftCommonJumpProcInterrupt(g);}
static void sonic_d_physics(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround){ftPhysicsSetGroundVelFriction(fp,0.25F*dMPCollisionMaterialFrictions[fp->coll_data.floor_flags&MAP_VERTEX_MAT_MASK]);ftPhysicsSetGroundVelTransferAir(g);}else if(fp->motion_vars.flags.flag2)ftPhysicsApplyAirVelDrift(g);else{FTAttributes a=*fp->attr;a.air_friction=3;ftPhysicsApplyGravityClampTVel(fp,2.25F,50);ftPhysicsApplyAirVelXFriction(fp,&a);}}
static void sonic_d_move_air(GObj *g){mpCommonSetFighterAir(ftGetStruct(g));sonic_enter(g,250);}
static void sonic_d_move_ground(GObj *g){mpCommonSetFighterGround(ftGetStruct(g));ftMainSetStatus(g,247,g->anim_frame,1,0);}
static void sonic_d_move_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->ga==nMPKineticsGround){if(mpCommonProcFighterOnFloor(g,sonic_d_move_air)&&fp->coll_data.mask_curr&(fp->lr>0?MAP_FLAG_LWALL:MAP_FLAG_RWALL))sonic_enter(g,248);}else if(fp->motion_vars.flags.flag2)mpCommonProcFighterCliffWaitOrLanding(g);else mpCommonProcFighterLanding(g,sonic_d_move_ground);}
static void sonic_d_end_air(GObj *g){mpCommonSetFighterAir(ftGetStruct(g));ftMainSetStatus(g,252,g->anim_frame,1,0);}
static void sonic_d_end_ground(GObj *g){mpCommonSetFighterGround(ftGetStruct(g));ftMainSetStatus(g,248,g->anim_frame,1,0);}
static void sonic_d_end_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,sonic_d_end_air);else mpCommonProcFighterLanding(g,sonic_d_end_ground);}
static void sonic_install(FighterDescriptor *d){memcpy(sonic_status,safe_statuses,sizeof(sonic_status));for(int a=228;a<=260;a++){if(a>228&&a<246)continue;int air=a==228||a>=249&&a!=256&&a!=258;FTStatusDesc *s=sonic_status+a-220;s->mflags.motion_id=a==228?203:a-27;s->mflags.attack_id=a==228?17:a<253?30:18;s->sflags.attack_id=s->mflags.attack_id;s->sflags.ga=air;s->proc_update=a==228?sonic_up_update:a==246||a==249?sonic_d_charge_update:a==247||a==250||a==251?sonic_d_move_update:a==253?sonic_n_begin_update:a==254||a==255?sonic_n_move_update:air?ftAnimEndSetFall:ftAnimEndSetWait;s->proc_interrupt=a==228?sonic_up_interrupt:a==250||a==251?sonic_d_interrupt:NULL;s->proc_physics=a==228?sonic_up_physics:a==247||a==250||a==251?sonic_d_physics:a==253?NULL:a==254||a==255?sonic_n_physics:air?ftPhysicsApplyAirVelFriction:ftPhysicsApplyGroundVelFriction;s->proc_map=a==228||a==260?mpCommonProcFighterCliffFloorCeil:a==246||a==249?sonic_d_charge_map:a==247||a==250||a==251?sonic_d_move_map:a==248||a==252?sonic_d_end_map:a==253?sonic_n_begin_map:a==254||a==255?sonic_n_move_map:sonic_n_end_map;}
 d->special_descs=sonic_status;d->special_handler[0]=d->special_handler[3]=sonic_n;d->special_handler[1]=d->special_handler[4]=sonic_up;d->special_handler[2]=sonic_dg;d->special_handler[5]=sonic_da;
}
