/* Additional Remix samples mixed into the same PCM output as native audio.
 * The source bank and every playback cursor are in checkpointed WASM memory. */
extern int port_remix_enabled(void);
static unsigned char *remix_sound_bank;
static unsigned remix_sound_size,remix_sound_count,remix_sound_next,remix_sound_plays;
static struct {unsigned id,pos,sub;int loop;} remix_sound_slots[24];
static unsigned remix_read32(const unsigned char *p){return p[0]|p[1]<<8|p[2]<<16|((unsigned)p[3]<<24);}
static int remix_sound_load(void){if(remix_sound_bank)return 1;FILE *f=port_fopen_staged("assets/remix/sounds.bank","rb");if(!f)return 0;fseek(f,0,SEEK_END);long n=ftell(f);rewind(f);if(n<8||n>128*1024*1024){fclose(f);return 0;}unsigned char *b=malloc(n);if(!b){fclose(f);return 0;}int ok=fread(b,1,n,f)==(size_t)n&&!memcmp(b,"RXS1",4);fclose(f);unsigned count=ok?remix_read32(b+4):0;if(!count||count>4096||8+20*count>(unsigned)n){free(b);return 0;}remix_sound_bank=b;remix_sound_size=n;remix_sound_count=count;return 1;}
int portRemixSoundPlay(unsigned id,int channel,int loop){if(!port_remix_enabled()||id<695||!remix_sound_load()||id>=remix_sound_count)return 0;unsigned char *e=remix_sound_bank+8+20*id;unsigned off=remix_read32(e),len=remix_read32(e+4),rate=remix_read32(e+8);if(!len||off>remix_sound_size||len>(remix_sound_size-off)/2||(rate!=16000&&rate!=32000))return 0;if(channel<0)channel=8+(remix_sound_next++%16);if(channel>=24)return 0;if(loop&&remix_sound_slots[channel].id==id)return 1;remix_sound_slots[channel].id=id;remix_sound_slots[channel].pos=remix_sound_slots[channel].sub=0;remix_sound_slots[channel].loop=loop;remix_sound_plays++;return 1;}
void portRemixSoundStop(int channel){if(channel>=0&&channel<24)remix_sound_slots[channel].id=0;}
static int remix_sound_playing(void){for(int i=0;i<24;i++)if(remix_sound_slots[i].id)return 1;return 0;}
unsigned portRemixSoundStatistics(int what){if(what==0)return remix_sound_plays;if(what==1)return remix_sound_count;unsigned active=0;for(int i=0;i<24;i++)if(remix_sound_slots[i].id)active++;return active;}
void portRemixSoundReset(void){memset(remix_sound_slots,0,sizeof(remix_sound_slots));remix_sound_next=0;}
static void remix_sound_mix(short *stereo,int count){if(!remix_sound_bank)return;for(int c=0;c<24;c++){if(!remix_sound_slots[c].id)continue;unsigned char *e=remix_sound_bank+8+20*remix_sound_slots[c].id;unsigned off=remix_read32(e),len=remix_read32(e+4),rate=remix_read32(e+8),ls=remix_read32(e+12),le=remix_read32(e+16);if(!le){ls=0;le=len;}for(int i=0;i<count;i++){unsigned p=remix_sound_slots[c].pos;if(p>=len||(remix_sound_slots[c].loop&&p>=le)){if(!remix_sound_slots[c].loop){remix_sound_slots[c].id=0;break;}p=remix_sound_slots[c].pos=ls;}const unsigned char *q=remix_sound_bank+off+2*p;int value=(short)(q[0]|q[1]<<8);for(int ch=0;ch<2;ch++){int v=stereo[i*2+ch]+value;stereo[i*2+ch]=(short)(v<-32768?-32768:v>32767?32767:v);}remix_sound_slots[c].sub+=rate;remix_sound_slots[c].pos+=remix_sound_slots[c].sub/32000;remix_sound_slots[c].sub%=32000;}}}
