/* DededeSpecial.asm: inhale, Super Dedede Jump and minion toss. */
static FTStatusDesc dedede_status[64];
static struct {int charge,timer;GObj *minion;} dedede_state[4];
#define DEDEDE(fp) (&dedede_state[(fp)->player])
static void dedede_enter(GObj *g,int a,u32 flags){remix_copy_set(g,64,a,0,1,flags);ftMainPlayAnimEventsAll(g);}
static void dedede_up(GObj *g){FTStruct *fp=ftGetStruct(g);marth_clear_flags(fp);dedede_enter(g,228,0);fp->physics.vel_ground.x=0;}
static void dedede_up_update(GObj *g){FTStruct *fp=ftGetStruct(g);switch(fp->status_id){case 228:if(g->anim_frame<=0)dedede_enter(g,229,1);break;case 230:if(fp->motion_vars.flags.flag0){Vec3f p={0,0,0};fp->motion_vars.flags.flag0=0;gmCollisionGetFighterPartsWorldPosition(fp->joints[0],&p);wpYoshiStarMakeStars(g,&p);}ftAnimEndSetWait(g);break;case 233:if(g->anim_frame<=0)ftCommonFallSpecialSetStatus(g,1,FALSE,FALSE,FALSE,1,FALSE);break;case 258:if(g->anim_frame<=0)dedede_enter(g,233,0);break;}}
static void dedede_up_interrupt(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->physics.vel_air.y<=0&&((fp->input.pl.button_tap&fp->input.button_mask_b)||fp->input.pl.stick_range.y< -39))dedede_enter(g,233,0);}
static void dedede_up_physics(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->status_id==228){if(!fp->motion_vars.flags.flag2){fp->physics.vel_air.x=fp->input.pl.stick_range.x*0.5F;fp->physics.vel_air.y=0;return;}if(fp->motion_vars.flags.flag2==1){mpCommonSetFighterAir(fp);fp->jumps_used=fp->attr->jumps_max;fp->physics.vel_air.x=fp->input.pl.stick_range.x*0.6875F;fp->physics.vel_air.y=144;fp->motion_vars.flags.flag2=2;}}
 float mult=fp->motion_vars.flags.flag1==0?2:fp->motion_vars.flags.flag1==1?0.19921875F:2.5F;ftPhysicsApplyGravityClampTVel(fp,fp->attr->gravity*mult,125);ftPhysicsApplyAirVelXFriction(fp,fp->attr);}
static void dedede_up_air(GObj *g){mpCommonSetFighterAir(ftGetStruct(g));}
static void dedede_up_map(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(fp->ga==nMPKineticsGround){mpCommonProcFighterOnFloor(g,dedede_up_air);return;}int landed=mpCommonCheckFighterPassCliff(g,ftSamusSpecialHiProcPass);if(fp->coll_data.mask_stat&MAP_FLAG_CLIFF_MASK){ftCommonCliffCatchSetStatus(g);return;}if(landed){if(a==233){ftCommonLandingFallSpecialSetStatus(g,FALSE,1);return;}mpCommonSetFighterGround(fp);fp->physics.vel_ground.x=0;if(a!=228)dedede_enter(g,a==258?10:230,0);return;}if((a==229||a==258)&&(fp->coll_data.mask_curr&MAP_FLAG_CEIL)){dedede_enter(g,258,0);fp->physics.vel_air.y=fp->physics.vel_air.z=0;func_800269C0_275C0(134);}}
static FTSpecialColl dedede_inhale_coll={100,0,{0,318,250},{480,330,330},0x18000000};
static void dedede_n_catch(GObj *g){ftKirbySpecialNCatchEatSetStatusParam(g,remix_copy_action(g,64,ftGetStruct(g)->ga==nMPKineticsAir?242:234));}
static void dedede_n_catchparams(FTStruct *fp){ftParamSetCatchParams(fp,FTCATCHKIND_MASK_KIRBYSPECIALN,dedede_n_catch,ftCommonCaptureKirbyProcCapture);}
static void dedede_n_loopcoll(FTStruct *fp){fp->is_reflect=TRUE;fp->special_coll=&dedede_inhale_coll;}
static void dedede_n(GObj *g){FTStruct *fp=ftGetStruct(g);dedede_enter(g,fp->ga==nMPKineticsAir?240:231,0);ftKirbySpecialNInitStatusVars(g,FALSE);dedede_n_catchparams(fp);if(fp->ga==nMPKineticsGround)fp->physics.vel_ground.x=0;}
static void dedede_n_wait(GObj *g){FTStruct *fp=ftGetStruct(g);dedede_enter(g,fp->ga==nMPKineticsAir?244:236,0xA0);ftParamSetCaptureImmuneMask(fp,FTCATCHKIND_MASK_ALL);}
static void dedede_n_spit(GObj *g){FTStruct *fp=ftGetStruct(g);dedede_enter(g,fp->ga==nMPKineticsAir?245:237,0xA4);ftParamSetCaptureImmuneMask(fp,FTCATCHKIND_MASK_ALL);}
static void dedede_star_physics(GObj *g){ftCommonThrownCommonStarUpdatePhysics(g,10);}
static void dedede_n_update(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,64),air=fp->ga==nMPKineticsAir;if(a==231||a==240){if(g->anim_frame<=0){dedede_enter(g,air?241:232,0x824);dedede_n_catchparams(fp);dedede_n_loopcoll(fp);}}else if(a==232||a==241)ftKirbySpecialNLoopProcUpdate(g);else if(a==234||a==242){if(!sonic_live(fp->catch_gobj,nGCCommonLinkIDFighter)){mpCommonSetFighterWaitOrFall(g);return;}Vec3f pos;ftKirbySpecialNAddCaptureDistance(fp,g,&pos);float dist=ftKirbySpecialNGetCaptureDistance(&DObjGetStruct(fp->catch_gobj)->translate.vec.f,&pos);if(dist<FTKIRBY_VACUUM_SPECIALNWAIT_DIST_MIN){ftGetStruct(fp->catch_gobj)->status_vars.common.capturekirby.is_goto_capturewait=TRUE;func_800269C0_275C0(nSYAudioFGMKirbySpecialNCopyEat);ftKirbySpecialNEatSetStatusParam(g,remix_copy_action(g,64,air?243:235));}else if(dist<FTKIRBY_VACUUM_STOPGFX_DIST_MIN)ftKirbySpecialNStopEffect(g);}else if(a==235||a==243){if(g->anim_frame<=0)dedede_n_wait(g);}else if(a==238||a==246){if(g->anim_frame<=0){ftKirbySpecialNWaitUpdateLR(g);dedede_n_wait(g);}}else if(a==237||a==245){if(fp->motion_vars.flags.flag2){fp->motion_vars.flags.flag2=0;if(sonic_live(fp->catch_gobj,nGCCommonLinkIDFighter)){GObj *v=fp->catch_gobj;FTStruct *vf=ftGetStruct(v);ftCommonThrownKirbyStarSetStatus(v);ftParamSetThrowParams(vf,g);vf->proc_physics=dedede_star_physics;vf->physics.vel_air=(Vec3f){-vf->lr*240,0,0};}else{Vec3f p={0,0,0};gmCollisionGetFighterPartsWorldPosition(fp->joints[16],&p);itStarRodWeaponStarMakeWeapon(g,&p,FALSE);}}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}else if(a==239||a==247){if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}}
static void dedede_n_interrupt(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,64),air=fp->ga==nMPKineticsAir;if(a==232||a==241){if(!ftKirbySpecialNLoopCheckContinueLoop(g))dedede_enter(g,air?247:239,0x24);return;}if(fp->input.pl.button_tap&(fp->input.button_mask_a|fp->input.button_mask_b)){if(fp->catch_gobj){ftKirbySpecialNApplyCaptureDamage(g,fp->catch_gobj,16);dedede_n_spit(g);}return;}if(fp->input.pl.stick_range.x*fp->lr<=-FTKIRBY_VACUUM_TURN_STICK_RANGE_MIN){dedede_enter(g,air?246:238,0xA4);ftParamSetCaptureImmuneMask(fp,FTCATCHKIND_MASK_ALL);return;}if(!air){int x=ABS(fp->input.pl.stick_range.x),next=x<8?236:ftCommonWalkGetWalkStatus(x)+244;if(a!=next){remix_copy_set(g,64,next,0,1,0xA4);ftParamSetCaptureImmuneMask(fp,FTCATCHKIND_MASK_ALL);}}}
static int dedede_n_air_id(int a){if(a>=255&&a<=257)return 244;return a<=232?a+9:a+8;}
static void dedede_n_switch(GObj *g,int air){FTStruct *fp=ftGetStruct(g);int old=remix_copy_current(fp,64),a=air?dedede_n_air_id(old):old<=241?old-9:old-8;if(air)mpCommonSetFighterAir(fp);else mpCommonSetFighterGround(fp);remix_copy_set(g,64,a,g->anim_frame,1,0x8A4);if(a==231||a==240||a==232||a==241)dedede_n_catchparams(fp);else ftParamSetCaptureImmuneMask(fp,FTCATCHKIND_MASK_ALL);if(a==232||a==241)dedede_n_loopcoll(fp);}
static void dedede_n_air(GObj *g){dedede_n_switch(g,1);}
static void dedede_n_ground(GObj *g){dedede_n_switch(g,0);}
int port_remix_dedede_capture_air(GObj *g){if(port_remix_enabled()&&remix_copy_kind(ftGetStruct(g),64)){dedede_n_air(g);return 1;}return 0;}
int port_remix_dedede_capture_wait(FTStruct *fp){return port_remix_enabled()&&remix_copy_kind(fp,64)&&(remix_copy_current(fp,64)==236||remix_copy_current(fp,64)==244||(remix_copy_current(fp,64)>=255&&remix_copy_current(fp,64)<=257));}
static void dedede_n_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,dedede_n_air);else mpCommonProcFighterLanding(g,dedede_n_ground);}
int port_remix_dedede_absorb_weapon(GObj *g){WPStruct *wp=wpGetStruct(g);GObj *f=wp->reflect_gobj;if(!port_remix_enabled()||!f||!remix_copy_kind(ftGetStruct(f),64)||ftGetStruct(f)->special_coll!=&dedede_inhale_coll)return 0;dedede_n_spit(f);if(wp->proc_absorb&&wp->proc_absorb(g))return 1;if(wp->proc_dead)wp->proc_dead(g);return 1;}
int port_remix_dedede_absorb_item(GObj *g){ITStruct *ip=itGetStruct(g);GObj *f=ip->reflect_gobj;if(!port_remix_enabled()||!f||!remix_copy_kind(ftGetStruct(f),64)||ftGetStruct(f)->special_coll!=&dedede_inhale_coll)return 0;dedede_n_spit(f);if(ip->proc_dead)ip->proc_dead(g);return 1;}
static void dedede_install(FighterDescriptor *d){memcpy(dedede_status,safe_statuses,sizeof(dedede_status));for(int a=228;a<=258;a++){if((a>=248&&a<=254))continue;FTStatusDesc *s=dedede_status+a-220;int up=a<=230||a==233||a==258,air=a==229||a==233||a==258||(a>=240&&a<=247);s->mflags.motion_id=a-25;s->mflags.attack_id=s->sflags.attack_id=up?17:18;s->sflags.ga=air;s->proc_update=up?dedede_up_update:dedede_n_update;s->proc_interrupt=a==229?dedede_up_interrupt:a==232||a==241||a==236||a==244||a>=255&&a<=257?dedede_n_interrupt:NULL;s->proc_physics=up?(a==230?ftPhysicsApplyGroundVelFriction:a==233?ftPhysicsApplyAirVelDrift:a==258?NULL:dedede_up_physics):a==237?ftPhysicsApplyGroundVelTransN:a==245?ftPhysicsApplyAirVelTransNAll:a>=255?ftCommonWalkProcPhysics:air?ftPhysicsApplyAirVelFriction:ftPhysicsApplyGroundVelFriction;s->proc_map=up?dedede_up_map:dedede_n_map;}d->special_descs=dedede_status;d->special_handler[0]=d->special_handler[3]=dedede_n;d->special_handler[1]=d->special_handler[4]=dedede_up;}
