/* GoemonSpecial.asm and items/Cloud.asm. */
static FTStatusDesc goemon_status[64];
static struct {int charge,charged,timer;GObj *cloud;} goemon_state[4];
#define GOEMON(fp) (&goemon_state[(fp)->player])
static void goemon_enter(GObj *g,int a){remix_copy_set(g,65,a,0,1,0);ftMainPlayAnimEventsAll(g);}
typedef struct {GObj *other;int charged,effect;} RyoState;
#define RYO(wp) ((RyoState*)&(wp)->weapon_vars)
_Static_assert(sizeof(RyoState)<=sizeof(((WPStruct*)0)->weapon_vars),"Ryo state fits");
static sb32 ryo_effect_update(GObj *g){WPStruct *wp=wpGetStruct(g);GObj *parent=RYO(wp)->other;if(!sonic_live(parent,nGCCommonLinkIDWeapon)||wpGetStruct(parent)->port_remix_origin!=65||RYO(wpGetStruct(parent))->other!=g)return TRUE;DObjGetStruct(g)->translate.vec.f=DObjGetStruct(parent)->translate.vec.f;return FALSE;}
static sb32 ryo_dead(GObj *g){WPStruct *wp=wpGetStruct(g);if(sonic_live(RYO(wp)->other,nGCCommonLinkIDWeapon)&&wpGetStruct(RYO(wp)->other)->port_remix_origin==65&&RYO(wpGetStruct(RYO(wp)->other))->other==g)RYO(wpGetStruct(RYO(wp)->other))->other=NULL;RYO(wp)->other=NULL;return TRUE;}
static sb32 ryo_hit(GObj *g){WPStruct *wp=wpGetStruct(g);if(RYO(wp)->charged){efManagerSparkleWhiteMultiExplodeMakeEffect(&DObjGetStruct(g)->translate.vec.f);func_800269C0_275C0(0);}else efManagerDustExpandSmallMakeEffect(&DObjGetStruct(g)->translate.vec.f,1);return ryo_dead(g);}
static sb32 ryo_update(GObj *g){WPStruct *wp=wpGetStruct(g);if(wpMainDecLifeCheckExpire(wp))return ryo_hit(g);DObjGetStruct(g)->rotate.vec.f.y-=RYO(wp)->charged?0.5F:0.3F;return FALSE;}
static sb32 ryo_map(GObj *g){return wpMapTestAllCheckCollEnd(g)?ryo_hit(g):FALSE;}
static void ryo_rotation(GObj *g){WPStruct *wp=wpGetStruct(g);DObj *d=DObjGetStruct(g);float yaw=wp->physics.vel_air.x<0?-HALF_PI32:HALF_PI32;d->rotate.vec.f=(Vec3f){yaw,0,HALF_PI32};if(sonic_live(RYO(wp)->other,nGCCommonLinkIDWeapon))DObjGetStruct(RYO(wp)->other)->rotate.vec.f.y=yaw;}
static sb32 ryo_reflect(GObj *g){wpSamusBombProcReflector(g);ryo_rotation(g);return FALSE;}
static sb32 ryo_hop(GObj *g){wpMarioFireballProcHop(g);ryo_rotation(g);return FALSE;}
static void goemon_ryo(GObj *g){FTStruct *fp=ftGetStruct(g);Vec3f p={0,0,0};gmCollisionGetFighterPartsWorldPosition(fp->joints[16],&p);p.y+=30;p.z=0;int charged=GOEMON(fp)->charged;WPDesc d={0};d.kind=nWPKindFireball;d.p_weapon=&main_files[65][5];d.o_attributes=charged?0x40:0;d.transform_types=(DObjTransformTypes){0x12,0x45,0};d.proc_update=ryo_update;d.proc_map=ryo_map;d.proc_hit=d.proc_shield=d.proc_setoff=d.proc_absorb=ryo_hit;d.proc_hop=ryo_hop;d.proc_reflector=ryo_reflect;GObj *w=wpManagerMakeWeapon(g,&d,&p,WEAPON_FLAG_PARENT_FIGHTER);if(!w)return;WPStruct *wp=wpGetStruct(w);memset(&wp->weapon_vars,0,sizeof(wp->weapon_vars));RYO(wp)->charged=charged;wp->lifetime=charged?60:40;wp->physics.vel_air=(Vec3f){(charged?130:100)*fp->lr,0,0};wp->proc_dead=ryo_dead;
 d.o_attributes=charged?0x80:0xC0;d.transform_types.tk2=0x48;d.proc_update=ryo_effect_update;d.proc_map=d.proc_hit=d.proc_shield=d.proc_setoff=d.proc_absorb=d.proc_hop=d.proc_reflector=NULL;GObj *e=wpManagerMakeWeapon(g,&d,&p,WEAPON_FLAG_PARENT_FIGHTER);if(e){WPStruct *ew=wpGetStruct(e);memset(&ew->weapon_vars,0,sizeof(ew->weapon_vars));RYO(ew)->other=w;RYO(ew)->effect=1;ew->attack_coll.attack_state=nGMAttackStateOff;ew->physics.vel_air=(Vec3f){0,0,0};RYO(wp)->other=e;}ryo_rotation(w);if(charged)func_800269C0_275C0(27);}
static void goemon_n(GObj *g){FTStruct *fp=ftGetStruct(g);marth_clear_flags(fp);GOEMON(fp)->charge=GOEMON(fp)->charged=0;goemon_enter(g,fp->ga==nMPKineticsAir?234:227);}
static void goemon_n_update(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,65),air=fp->ga==nMPKineticsAir;if(a==227||a==234){if(fp->motion_vars.flags.flag1&&!(fp->input.pl.button_hold&fp->input.button_mask_b))goemon_enter(g,air?236:233);else if(g->anim_frame<=0)goemon_enter(g,air?235:228);}else if(a==233||a==236){if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=0;goemon_ryo(g);}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}else{if(GOEMON(fp)->charge++==18){GOEMON(fp)->charged=1;func_800269C0_275C0(28);func_800269C0_275C0(65);}if(!(fp->input.pl.button_hold&fp->input.button_mask_b))goemon_enter(g,air?236:233);}}
static void goemon_n_walk(GObj *g){FTStruct *fp=ftGetStruct(g);int x=fp->input.pl.stick_range.x*fp->lr,a=x< -44?232:x< -9?231:x<10?228:x<45?229:230,old=remix_copy_current(fp,65);if(old==a)return;const float cycles[]={40,80,60,80,60};float frame=old==228||a==228?0:g->anim_frame*cycles[a-228]/cycles[old-228];remix_copy_set(g,65,a,frame,1,0x802);}
static void goemon_n_physics(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,65);if(fp->ga==nMPKineticsGround){if(a>=229&&a<=232){ftPhysicsSetGroundVelAbsStickRange(fp,a>=231?-0.25F:0.25F,30);ftPhysicsSetGroundVelTransferAir(g);}else ftPhysicsApplyGroundVelFriction(g);}else{if(fp->is_fastfall)ftPhysicsApplyFastFall(fp,fp->attr);else ftPhysicsApplyGravityDefault(fp,fp->attr);if(!ftPhysicsCheckClampAirVelXDecMax(fp,fp->attr)){ftPhysicsClampAirVelXStickRange(fp,8,fp->attr->air_accel,28);ftPhysicsApplyAirVelXFriction(fp,fp->attr);}}}
static void goemon_n_air(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,65)==227?234:remix_copy_current(fp,65)==233?236:235;mpCommonSetFighterAir(fp);remix_copy_set(g,65,a,g->anim_frame,1,0x802);ftPhysicsClampAirVelXMax(fp);}
static void goemon_n_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int a=remix_copy_current(fp,65)==234?227:remix_copy_current(fp,65)==236?233:228;mpCommonSetFighterGround(fp);remix_copy_set(g,65,a,g->anim_frame,1,0x802);}
static void goemon_n_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,goemon_n_air);else mpCommonProcFighterLanding(g,goemon_n_ground);}
static sb32 goemon_cloud_update(GObj *g){ITStruct *ip=itGetStruct(g);if(ip->multi){if(--ip->lifetime<=0){func_800269C0_275C0(0x501);return TRUE;}if(ip->lifetime<22)DObjGetStruct(g)->flags=ip->lifetime&2?DOBJ_FLAG_HIDDEN:0;return FALSE;}GObj *owner=ip->owner_gobj;if(!sonic_live(owner,nGCCommonLinkIDFighter))return TRUE;FTStruct *fp=ftGetStruct(owner);int a=fp->status_id;if(a!=223&&a!=224){ip->multi=1;ip->lifetime=a==225||a==226?30:1;ip->physics.vel_air=(Vec3f){fp->coll_data.pos_diff.x*0.5F,fp->coll_data.pos_diff.y*0.5F,0};DObjGetStruct(g)->flags=0;return FALSE;}DObjGetStruct(g)->translate.vec.f=DObjGetStruct(owner)->translate.vec.f;if(GOEMON(fp)->timer>=70)DObjGetStruct(g)->flags=GOEMON(fp)->timer&2?DOBJ_FLAG_HIDDEN:0;return FALSE;}
static void goemon_cloud(GObj *g){Vec3f p=DObjGetStruct(g)->translate.vec.f,v={0,0,0};ITDesc d={0};d.kind=nITKindCapsule;d.p_file=&main_files[65][6];d.o_attributes=0x40;d.transform_types=(DObjTransformTypes){0x1B,0,0};d.proc_update=goemon_cloud_update;GObj *it=itManagerMakeItem(g,&d,&p,&v,ITEM_FLAG_PARENT_FIGHTER);GOEMON(ftGetStruct(g))->cloud=it;if(it){ITStruct *ip=itGetStruct(it);ip->owner_gobj=g;ip->player=ftGetStruct(g)->player;ip->team=ftGetStruct(g)->team;ip->multi=0;ip->is_allow_pickup=FALSE;ip->damage_coll.hitstatus=nGMHitStatusNone;ip->attack_coll.attack_state=nGMAttackStateOff;gcAddXObjForDObjFixed(DObjGetStruct(it),0x2E,0);}}
static void goemon_up(GObj *g){FTStruct *fp=ftGetStruct(g);int ground=fp->ga==nMPKineticsGround;if(ground){mpCommonSetFighterAir(fp);fp->physics.vel_air.y=80;}marth_clear_flags(fp);goemon_enter(g,223);fp->physics.vel_air.y*=0.375F;fp->motion_vars.flags.flag1=1;fp->is_fastfall=FALSE;fp->jumps_used=fp->attr->jumps_max;GOEMON(fp)->timer=0;goemon_cloud(g);func_800269C0_275C0(0x500);}
static void goemon_up_state(GObj *g,int a){goemon_enter(g,a);ftGetStruct(g)->motion_vars.flags.flag1=1;}
static void goemon_turn(FTStruct *fp){if(fp->input.pl.stick_range.x*fp->lr<=-40)fp->lr=-fp->lr;}
static void goemon_up_fall(GObj *g){ftCommonFallSpecialSetStatus(g,0.9375F,FALSE,TRUE,FALSE,0.25F,FALSE);}
static void goemon_up_update(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(a==223||a==224){if(GOEMON(fp)->timer++>=80){if(a==223){goemon_turn(fp);goemon_up_state(g,225);}else goemon_up_fall(g);}else if(a==224&&g->anim_frame<=0)goemon_up_state(g,223);}else{if(a==225&&fp->motion_vars.flags.flag0==1){fp->motion_vars.flags.flag0=2;fp->physics.vel_air.y=64;}if(g->anim_frame<=0)goemon_up_fall(g);}}
static void goemon_up_interrupt(GObj *g){FTStruct *fp=ftGetStruct(g);int tap=fp->input.pl.button_tap;if(tap&(fp->input.button_mask_a|fp->input.button_mask_b)){goemon_turn(fp);goemon_up_state(g,224);}else if(tap&fp->input.button_mask_z){fp->physics.vel_air.y=14;goemon_up_state(g,226);}else if(tap&(U_CBUTTONS|D_CBUTTONS|L_CBUTTONS|R_CBUTTONS)){goemon_turn(fp);goemon_up_state(g,225);}}
static void goemon_up_physics(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->status_id==226||(fp->status_id==225&&fp->motion_vars.flags.flag0)){ftPhysicsApplyAirVelDriftFastFall(g);return;}float x=fp->input.pl.stick_range.x,y=fp->input.pl.stick_range.y,tx=0,ty=0;if(ABSF(x)<11&&ABSF(y)<11){if(sqrtf(SQUARE(fp->physics.vel_air.x)+SQUARE(fp->physics.vel_air.y))<=3){fp->physics.vel_air.x=fp->physics.vel_air.y=0;return;}}else{tx=x*0.53125F;ty=y*0.53125F;float len=sqrtf(tx*tx+ty*ty);if(len>=42.5F){tx*=42.5F/len;ty*=42.5F/len;}}float angle=syUtilsArcTan2(ty-fp->physics.vel_air.y,tx-fp->physics.vel_air.x);fp->physics.vel_air.x+=2*cosf(angle);fp->physics.vel_air.y+=2*sinf(angle);}
static void goemon_up_map(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->physics.vel_air.y>=0)mpCommonCheckFighterProject(g);else if(mpCommonCheckFighterPassCliff(g,ftSamusSpecialHiProcPass)){if(fp->coll_data.mask_stat&MAP_FLAG_CLIFF_MASK)ftCommonCliffCatchSetStatus(g);else ftCommonLandingFallSpecialSetStatus(g,FALSE,fp->status_id==247?0.4375F:0.25F);}}
static void goemon_install(FighterDescriptor *d){memcpy(goemon_status,safe_statuses,sizeof(goemon_status));for(int a=223;a<=236;a++){FTStatusDesc *s=goemon_status+a-220;int up=a<=226,air=up||a>=234;s->mflags.motion_id=up?a-25:a-14;s->mflags.attack_id=s->sflags.attack_id=up?17:18;s->sflags.ga=air;s->proc_update=up?goemon_up_update:goemon_n_update;s->proc_interrupt=a==223?goemon_up_interrupt:a>=228&&a<=232?goemon_n_walk:NULL;s->proc_physics=up?goemon_up_physics:goemon_n_physics;s->proc_map=up?goemon_up_map:goemon_n_map;}d->special_descs=goemon_status;d->special_handler[0]=d->special_handler[3]=goemon_n;d->special_handler[1]=d->special_handler[4]=goemon_up;}
static void goemon_d_pull(GObj *g){FTStruct *fp=ftGetStruct(g);float frame=fp->motion_vars.flags.flag1;ftMainSetStatus(g,fp->ga==nMPKineticsAir?243:238,frame,1,2);ftMainPlayAnimEventsAll(g);ftParamSetCaptureImmuneMask(fp,FTCATCHKIND_MASK_ALL);fp->catch_gobj=fp->search_gobj;marth_clear_flags(fp);if(fp->ga==nMPKineticsAir)fp->physics.vel_air.x=fp->physics.vel_air.y=0;func_800269C0_275C0(0x13);}
static void goemon_down(GObj *g){FTStruct *fp=ftGetStruct(g);goemon_enter(g,fp->ga==nMPKineticsAir?242:237);ftYoshiSpecialNSetCatchParams(fp,goemon_d_pull);marth_clear_flags(fp);fp->is_fastfall=FALSE;}
static void goemon_d_launch(GObj *g,int wall){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterAir(fp);if(!fp->jumps_used)fp->jumps_used=1;goemon_enter(g,wall?247:245);fp->physics.vel_air.x=(wall?24:64)*fp->lr;fp->physics.vel_air.y=36;if(wall)fp->motion_vars.flags.flag1=1;}
static void goemon_d_update(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(a==237||a==242){if(fp->motion_vars.flags.flag1)fp->motion_vars.flags.flag1--;if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}else if(a==238||a==243){int ending=g->anim_frame<=0;ftCommonThrowProcUpdate(g);if(ending)goemon_d_launch(g,0);}else if(a==239||a==244){if(g->anim_frame<=0)goemon_d_launch(g,1);}else if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}
static void goemon_d_air(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id+5;mpCommonSetFighterAir(fp);ftMainSetStatus(g,a,g->anim_frame,1,3);if(a==242)ftYoshiSpecialNSetCatchParams(fp,goemon_d_pull);}
static void goemon_d_ground(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id-5;mpCommonSetFighterGround(fp);ftMainSetStatus(g,a,g->anim_frame,1,3);if(a==237)ftYoshiSpecialNSetCatchParams(fp,goemon_d_pull);}
/* Sweep a narrow collision diamond at the animated chain tip, using the same
 * wall solver as the fighter. The temporary collision state cannot move Goemon. */
static int goemon_chain_wall(FTStruct *fp){Vec3f p={0,0,0};gmCollisionGetFighterPartsWorldPosition(fp->joints[25],&p);float initial=p.x;MPCollData c=fp->coll_data;c.p_translate=&p;c.map_coll=(MPObjectColl){10,5,0,40};c.p_map_coll=&c.map_coll;int result=0,broken=0;if(mpProcessCheckTestLWallCollisionAdjNew(&c)){mpProcessRunLWallCollisionAdjNew(&c);broken=ABSF(initial-p.x)>400;p.x=initial;result=1;if(!broken)return result;}if(mpProcessCheckTestRWallCollisionAdjNew(&c)){mpProcessRunRWallCollisionAdjNew(&c);broken=ABSF(initial-p.x)>400;result=2;}return broken?3:result;}
static void goemon_d_map(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id,air=fp->ga==nMPKineticsAir;if(a==247){goemon_up_map(g);return;}if((a==237||a==242)&&fp->motion_vars.flags.flag2){int result=goemon_chain_wall(fp);if(result==3||(result&(fp->lr>0?1:2))){float frame=fp->motion_vars.flags.flag1;ftMainSetStatus(g,result==3?(air?246:241):(air?244:239),frame,result==3?2:1,2);ftMainPlayAnimEventsAll(g);if(result!=3){marth_clear_flags(fp);if(air)fp->physics.vel_air.x=fp->physics.vel_air.y=0;func_800269C0_275C0(0x13);}else if(air)fp->jumps_used=fp->attr->jumps_max;return;}}
 if(air)mpCommonProcFighterLanding(g,goemon_d_ground);else mpCommonProcFighterOnFloor(g,goemon_d_air);}
static void goemon_down_install(FighterDescriptor *d){const int motions[]={204,205,205,206,207,208,209,209,210,211,212};for(int a=237;a<=247;a++){FTStatusDesc *s=goemon_status+a-220;int air=a>=242,pull=a==238||a==239||a==243||a==244;s->mflags.motion_id=motions[a-237];s->mflags.attack_id=s->sflags.attack_id=30;s->sflags.ga=air;s->proc_update=goemon_d_update;s->proc_interrupt=NULL;s->proc_physics=air?(pull?ftPhysicsApplyAirVelTransNAll:a==245?ftPhysicsApplyAirVelFriction:a==247?ftPhysicsApplyAirVelDriftFastFall:ftPhysicsApplyAirVelDrift):(pull?ftPhysicsApplyGroundVelTransN:ftPhysicsApplyGroundVelFriction);s->proc_map=goemon_d_map;}d->special_handler[2]=d->special_handler[5]=goemon_down;}
