/* CrashSpecial.asm: Death Tornado Spin, Super Belly Flop, and Dig. */
static FTStatusDesc crash_status[64];
static struct {int blocked,hitlag_over,timer;float x,y,ground;GObj *dig;FTAttributes attr;} crash_state[4];
#define CRASH(fp) (&crash_state[(fp)->player])
extern EFDesc dEFManagerLinkSpinAttackEffectDesc;
static void crash_enter(GObj *g,int a){marth_clear_flags(ftGetStruct(g));remix_copy_set(g,72,a,0,1,0);ftMainPlayAnimEventsAll(g);}
static void crash_dig_effect_update(GObj *g){EFStruct *ep=efGetStruct(g);GObj *owner=ep->fighter_gobj;if(!sonic_live(owner,nGCCommonLinkIDFighter)){efManagerSetPrevStructAlloc(ep);gcEjectGObj(g);return;}FTStruct *fp=ftGetStruct(owner);if(remix_copy_current(fp,72)<227||remix_copy_current(fp,72)>229){CRASH(fp)->dig=NULL;efManagerSetPrevStructAlloc(ep);gcEjectGObj(g);return;}if(!ep->is_pause_effect&&g->anim_frame>0)gcPlayAnimAll(g);DObj *root=DObjGetStruct(g);root->rotate.vec.f.y=fp->lr*HALF_PI32;root->rotate.vec.f.z=-syUtilsArcTan2(fp->coll_data.floor_angle.x,fp->coll_data.floor_angle.y);}
static GObj *crash_effect(GObj *g,int dig){FTStruct *fp=ftGetStruct(g);if(!main_files[72][6])return NULL;EFDesc d=dEFManagerLinkSpinAttackEffectDesc;d.file_head=dig?(void**)((char*)main_files[72][6]+0xCC0):&main_files[72][6];d.o_dobjsetup=dig?0x230:0x708;d.o_mobjsub=dig?0x340:0x838;d.o_anim_joint=dig?0x378:0x894;d.o_matanim_joint=dig?0x394:0x8B4;if(dig)d.proc_update=crash_dig_effect_update;GObj *e=efManagerMakeEffectNoForce(&d);if(e){efGetStruct(e)->fighter_gobj=g;DObjGetStruct(e)->user_data.p=fp->joints[0];DObjGetStruct(e)->rotate.vec.f.y=fp->lr*HALF_PI32;fp->is_effect_attach=TRUE;fp->proc_lagstart=ftParamProcPauseEffect;fp->proc_lagend=ftParamProcResumeEffect;}return e;}
static void crash_n(GObj *g){FTStruct *fp=ftGetStruct(g);int air=fp->ga==nMPKineticsAir;crash_enter(g,air?224:223);fp->physics.vel_air.x*=air?1.25F:1.5F;fp->is_fastfall=FALSE;CRASH(fp)->blocked=CRASH(fp)->hitlag_over=0;crash_effect(g,0);}
void port_remix_crash_contact(FTStruct *fp,int type){if(port_remix_enabled()&&remix_copy_kind(fp,72)&&(remix_copy_current(fp,72)==223||remix_copy_current(fp,72)==224)&&type==nGMHitTypeShield)CRASH(fp)->blocked=1;}
static void crash_n_air(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterAir(fp);remix_copy_set(g,72,remix_copy_current(fp,72)+1,g->anim_frame,1,7);}
static void crash_n_ground(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterGround(fp);remix_copy_set(g,72,remix_copy_current(fp,72)-1,g->anim_frame,1,7);}
static ITStatusDesc crash_flung_status[1];
static void crash_fling(GObj *g){Vec3f p=DObjGetStruct(g)->translate.vec.f;for(GObj *it=gGCCommonLinks[nGCCommonLinkIDItem];it;it=it->link_next){ITStruct *ip=itGetStruct(it);Vec3f q=DObjGetStruct(it)->translate.vec.f;if(!ip->is_hold&&ip->is_allow_pickup&&ABSF(q.x-p.x)<=300&&ABSF(q.y-p.y-300)<=300){ip->physics.vel_air.x=q.x>=p.x?300:-300;ip->is_allow_pickup=FALSE;itMapSetAir(ip);itMainSetStatus(it,crash_flung_status,0);func_800269C0_275C0(0x5BD);break;}}}
static void crash_n_update(GObj *g){FTStruct *fp=ftGetStruct(g);__typeof__(crash_state[0])*s=CRASH(fp);if(s->blocked){s->blocked=0;s->x=fp->physics.vel_air.x*0.25F;s->y=fp->physics.vel_air.y*0.5F;s->ground=fp->physics.vel_ground.x*0.5F;crash_enter(g,fp->ga==nMPKineticsAir?226:225);fp->physics.vel_air.x=fp->physics.vel_air.y=fp->physics.vel_ground.x=0;s->hitlag_over=0;return;}if(remix_copy_current(fp,72)>=225){if(fp->motion_vars.flags.flag1){fp->motion_vars.flags.flag1=0;s->hitlag_over=1;fp->physics.vel_air.x=s->x;fp->physics.vel_air.y=s->y;fp->physics.vel_ground.x=s->ground;}}else{if(fp->ga==nMPKineticsGround&&!fp->motion_vars.flags.flag1&&ftCommonKneeBendGetInputTypeCommon(fp)){crash_n_air(g);fp->physics.vel_air.y=72;return;}crash_fling(g);}if(g->anim_frame<=0)mpCommonSetFighterWaitOrFall(g);}
/* The source deliberately holds velocity when the target is within two units. */
static void crash_steer(FTStruct *fp,float multiplier,float acceleration,float cap,int ending){float x=fp->physics.vel_air.x,target=fp->input.pl.stick_range.x*multiplier;if(ending)target=0;else if(ABSF(fp->input.pl.stick_range.x)<11){target=0;if(ABSF(x)<=2){fp->physics.vel_air.x=fp->physics.vel_ground.x=0;return;}}float diff=target-x;if(ABSF(diff)>=2)x+=diff>0?acceleration:-acceleration;if(x>cap)x=cap;if(x< -cap)x=-cap;fp->physics.vel_air.x=x;if(fp->ga==nMPKineticsGround)fp->physics.vel_ground.x=x*fp->lr;}
static void crash_n_physics(GObj *g){FTStruct *fp=ftGetStruct(g);if(remix_copy_current(fp,72)>=225){if(fp->ga==nMPKineticsGround)ftPhysicsApplyGroundVelFriction(g);else if(CRASH(fp)->hitlag_over)ftPhysicsApplyAirVelDrift(g);return;}int air=fp->ga==nMPKineticsAir,ending=!air&&fp->motion_vars.flags.flag1;crash_steer(fp,air?0.5F:0.625F,ending?4.5F:!air&&ABSF(fp->input.pl.stick_range.x)<11?1.25F:2,78,ending);if(air)ftPhysicsApplyGravityClampTVel(fp,2.625F,48);}
static void crash_n_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonProcFighterOnFloor(g,crash_n_air);else mpCommonProcFighterLanding(g,crash_n_ground);}
static void crash_up(GObj *g){FTStruct *fp=ftGetStruct(g);int air=fp->ga==nMPKineticsAir;crash_enter(g,air?234:233);fp->physics.vel_air.y=air?fp->physics.vel_air.y*0.048828125F:0;fp->is_fastfall=FALSE;}
static void crash_up_update(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->motion_vars.flags.flag0){fp->motion_vars.flags.flag0=0;mpCommonSetFighterAir(fp);fp->physics.vel_air.y=56;fp->jumps_used=fp->attr->jumps_max;}}
static void crash_up_turn(GObj *g){FTStruct *fp=ftGetStruct(g);if(fp->motion_vars.flags.flag2){fp->motion_vars.flags.flag1=1;wolf_up_turn(g);fp->motion_vars.flags.flag1=fp->motion_vars.flags.flag2=0;}}
static void crash_up_physics(GObj *g){FTStruct *fp=ftGetStruct(g);int fall=fp->motion_vars.flags.flag1;ftPhysicsApplyGravityClampTVel(fp,fall?18:1.5F,120);if(fall&&ftPhysicsCheckClampAirVelXDecMax(fp,fp->attr))return;ftPhysicsClampAirVelXStickRange(fp,8,fall?0.050048828125F:0.080078125F,fall?20:48);FTAttributes a=*fp->attr;a.air_friction=2;ftPhysicsApplyAirVelXFriction(fp,&a);}
static void crash_up_land(GObj *g){FTStruct *fp=ftGetStruct(g);mpCommonSetFighterGround(fp);crash_enter(g,235);fp->physics.vel_ground.x=0;}
static void crash_up_map(GObj *g){if(ftGetStruct(g)->ga==nMPKineticsGround)mpCommonSetFighterFallOnEdgeBreak(g);else mpCommonProcFighterCliff(g,crash_up_land);}
static void crash_d_begin(GObj *g,int landed){FTStruct *fp=ftGetStruct(g);if(landed)mpCommonSetFighterGround(fp);marth_clear_flags(fp);ftMainSetStatus(g,227,landed?20:0,1,7);ftMainPlayAnimEventsAll(g);CRASH(fp)->dig=crash_effect(g,1);}
static void crash_down(GObj *g){FTStruct *fp=ftGetStruct(g);CRASH(fp)->timer=180;CRASH(fp)->dig=NULL;if(fp->ga==nMPKineticsAir){crash_enter(g,232);fp->physics.vel_air.x=0;fp->physics.vel_air.y=30;}else if(fp->coll_data.floor_flags&MAP_VERTEX_COLL_PASS){crash_enter(g,231);fp->physics.vel_air.x=0;}else crash_d_begin(g,0);}
static void crash_d_end(GObj *g,int edge){FTStruct *fp=ftGetStruct(g);crash_enter(g,230);mpCommonSetFighterAir(fp);fp->physics.vel_air.y=edge?40:60;}
static void crash_d_edge(GObj *g){crash_d_end(g,1);}
static void crash_d_update(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(a==227){if(g->anim_frame<=0){CRASH(fp)->timer=180;ftMainSetStatus(g,228,0,1,7);ftMainPlayAnimEventsAll(g);}return;}if(a==228||a==229){if(a==229&&fp->motion_vars.flags.flag1){fp->motion_vars.flags.flag1=0;fp->lr=-fp->lr;}if(--CRASH(fp)->timer<=0||!(fp->input.pl.button_hold&fp->input.button_mask_b)){crash_d_end(g,0);return;}if(a==228&&fp->input.pl.stick_range.x*fp->lr<=-11){ftMainSetStatus(g,229,0,1,7);ftMainPlayAnimEventsAll(g);}else if(a==229&&g->anim_frame<=0){ftMainSetStatus(g,228,0,1,7);ftMainPlayAnimEventsAll(g);}return;}if(a==231||a==232){if(fp->motion_vars.flags.flag1){fp->coll_data.ignore_line_id=fp->coll_data.floor_line_id;mpCommonSetFighterAir(fp);fp->physics.vel_air.y=-100;}return;}ftAnimEndSetFall(g);}
static void crash_d_physics(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(a==227)ftPhysicsApplyGroundVelFriction(g);else if(a==228||a==229)crash_steer(fp,0.5F,8,40,0);else if(a==230)ftPhysicsApplyAirVelDriftFastFall(g);else if(fp->ga==nMPKineticsAir){ftPhysicsApplyGravityClampTVel(fp,fp->motion_vars.flags.flag1?7:0.5F,100);if(!ftPhysicsCheckClampAirVelXDecMax(fp,fp->attr)){ftPhysicsClampAirVelXStickRange(fp,8,fp->attr->air_accel,fp->attr->air_speed_max_x);FTAttributes a=*fp->attr;a.air_friction=1.75F;ftPhysicsApplyAirVelXFriction(fp,&a);}}}
static void crash_d_land(GObj *g){crash_d_begin(g,1);}
static void crash_d_map(GObj *g){FTStruct *fp=ftGetStruct(g);int a=fp->status_id;if(a==228||a==229)mpCommonProcFighterOnFloor(g,crash_d_edge);else if(a==230)mpCommonProcFighterCliffWaitOrLanding(g);else if(fp->ga==nMPKineticsGround)mpCommonSetFighterFallOnEdgeBreak(g);else mpCommonProcFighterLanding(g,crash_d_land);}
static int crash_ecb(FTStruct *fp,int status,float *top,float *center){if(fp->attr!=&CRASH(fp)->attr){CRASH(fp)->attr=*fp->attr;fp->attr=&CRASH(fp)->attr;}*top=status==228||status==229?150:320;*center=status==228||status==229?80:190;return 1;}
static void crash_install(FighterDescriptor *d){d->ecb_override=crash_ecb;memcpy(crash_status,safe_statuses,sizeof(crash_status));for(int a=223;a<=235;a++){FTStatusDesc *s=crash_status+a-220;int n=a<=226,up=a>=233,air=a==224||a==226||a==230||a==232||a==234;s->mflags.motion_id=a<227?a-25:a-23;s->mflags.attack_id=s->sflags.attack_id=n?18:up?17:30;s->sflags.ga=air;s->proc_update=n?crash_n_update:up?(a==235?ftAnimEndSetWait:crash_up_update):crash_d_update;s->proc_interrupt=up&&a!=235?crash_up_turn:NULL;s->proc_physics=n?crash_n_physics:up?(a==235?ftPhysicsApplyGroundVelFriction:crash_up_physics):crash_d_physics;s->proc_map=n?crash_n_map:up?(a==235?mpCommonProcFighterOnCliffEdge:crash_up_map):crash_d_map;}d->special_descs=crash_status;d->special_handler[0]=d->special_handler[3]=crash_n;d->special_handler[1]=d->special_handler[4]=crash_up;d->special_handler[2]=d->special_handler[5]=crash_down;}
