import {ACTIVE_PROFILE} from './game-profile.mjs';
import {FIGHTER_NAMES,STAGE_NAMES,ratingSummary} from './competitive-set.mjs';
export function createCompetitiveUI({onQueue,onJoinInvite,onBack,onPick,onSelection,onReady,onStart,onReturnLobby,profile=ACTIVE_PROFILE,readController=()=>null}){
 const root=document.createElement('section');root.id='competitive';root.hidden=true;root.setAttribute('aria-label','Competitive online');document.getElementById('play-surface').append(root);
 let selected=0,lastView=null;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,action,cls)=>{const b=el('button',text,cls);b.type='button';b.onclick=action;return b;};
 function base(kicker,title,subtitle){root.replaceChildren();root.classList.remove('native-result');root.hidden=false;document.body.classList.add('competitive-open');const card=el('div',null,'competitive-card');root.append(card);card.append(el('p',kicker,'competitive-kicker'),el('h1',title),el('p',subtitle,'competitive-subtitle'));return card;}
 function grid(card,locked=false){const g=el('div',null,'fighter-grid');g.setAttribute('role','group');g.setAttribute('aria-label','Fighters');for(const id of profile.fighters){const b=button(FIGHTER_NAMES[id],()=>{selected=id;for(const c of g.children)c.setAttribute('aria-pressed',String(Number(c.dataset.fighter)===id));});b.dataset.fighter=id;b.setAttribute('aria-pressed',String(id===selected));b.disabled=locked;g.append(b);}card.append(g);}
 function setup(){lastView=null;const card=base(`${profile.title.toUpperCase()} / ONLINE`,'Play together','Choose how to play. Select your fighter once you enter the lobby.');
 const modes=el('div',null,'queue-grid');
 for(const [queue,title,copy] of [['casual','Casual','Two humans · one game'],['ranked','Ranked','Two humans · best of three'],['friends','Friends','Up to four humans · shared devices welcome']]){const b=button('',()=>onQueue(queue),'queue-card');b.append(el('strong',title),el('span',copy));modes.append(b);}card.append(modes,button('Back to local play',()=>onBack(selected),'quiet'));
 }
 function lobby(view){const focus=document.activeElement?.textContent;lastView=view;const card=base(`${profile.title.toUpperCase()} / LOBBY`,view.waitingNext?'Next game':'Choose your fighter',view.waitingNext?'A game is in progress. Your controller port is reserved for the next game.':view.participants.length<2?'Waiting for another player. Invite friends through the YouGame lobby controls.':'Each player chooses a fighter and confirms Ready.');
 const seats=el('div',null,'set-score');for(let slot=0;slot<(view.capacity||4);slot++){const p=view.participants.find(p=>p.slot===slot),seat=el('div');seat.append(el('strong',`P${slot+1}`),el('span',p?.name||'Waiting for player'),el('small',p?(p.ready?'Ready':FIGHTER_NAMES[p.selection]||'Choosing fighter'):'Empty controller port'));seats.append(seat);}card.append(seats);
 const locals=view.participants.filter(p=>p.local);let active=locals.find(p=>p.id===selectedParticipant)||locals[0];if(active){selectedParticipant=active.id;const tabs=el('div',null,'queue-grid');for(const p of locals)tabs.append(button(`Choose for P${p.slot+1}`,()=>{selectedParticipant=p.id;lobby(view);}));card.append(tabs);selected=active.selection??profile.fighters[0];const g=el('div',null,'fighter-grid');for(const id of profile.fighters){const b=button(FIGHTER_NAMES[id],()=>onSelection(active.id,id));b.setAttribute('aria-pressed',String(id===active.selection));b.disabled=view.starting;g.append(b);}card.append(g);const ready=button(active.ready?'Not ready':`Ready · P${active.slot+1}`,()=>onReady(active.id),'primary');ready.disabled=active.selection===null||view.starting;card.append(ready);}
 if(view.host){const start=button(view.starting?'Starting…':'Start match',onStart,'primary');start.disabled=!view.canStart;card.append(start);}else card.append(el('p','The lobby host starts once everyone is ready.','rules-note'));
 card.append(el('p','Invite friends, add a local player, or leave through the YouGame lobby controls.','rules-note'),button('Leave lobby',()=>onBack(selected),'quiet'));
 if(focus)[...root.querySelectorAll('button')].find(b=>b.textContent===focus)?.focus({preventScroll:true});
 }
 let selectedParticipant=null;
 function show(view,players=[]){lastView=view;if(view.phase==='playing'){hide();return;}const names=players.map((p,i)=>p.name||`Player ${i+1}`),own=view.turn===view.seat;
 const titles={connecting:'Connecting the set',confirming:'Confirming game result',counterpick:own?'Your character counterpick':'Opponent is choosing',replay:'Tie · replaying the game',complete:'Set complete'};
 const card=base(view.ranked?'RANKED / BEST OF THREE':view.private?'FRIENDS / ONE GAME':'CASUAL / ONE GAME',titles[view.phase]||'Preparing game',view.phase==='counterpick'?'The previous winner locks first. The losing player chooses second.':'Both players must agree before the set advances.');
 const score=el('div',null,'set-score');for(let i=0;i<view.wins.length;i++){const p=el('div');p.append(el('span',`${names[i]}${i===view.seat?' · YOU':''}`),el('strong',String(view.wins[i])),el('small',FIGHTER_NAMES[view.fighters[i]]||'Selecting'));score.append(p);}card.append(score,el('p',`Game ${view.game} · ${STAGE_NAMES[view.stage]}`,'stage-label'));
 if(view.ranked)card.append(el('p','Dream Land is the only ranked stage. No strikes or stage bans are needed.','rules-note'));
 if(view.phase==='counterpick'){selected=view.fighters[view.seat];grid(card,!own);const lock=button('Lock fighter',()=>onPick(selected),'primary');lock.disabled=!own;card.append(lock);}
 if(view.history.length)card.append(el('p',view.history.map(g=>`G${g.game}: ${g.winner===2?'Tie':names[g.winner]+' won'} on ${STAGE_NAMES[g.stage]}`).join(' · '),'rules-note'));
 }
 function result(event,view,{native=false}={}){const winner=view?.participants?.find(p=>p.id===(event.winner??event.ranking?.[0]));const card=base(`${profile.title.toUpperCase()} / RESULT`,event.void?'Match void':event.draw?'Draw':winner?`${winner.name} won`:event.won?'You won':'Match complete',event.ranked?'Your ranked match is complete.':'Stay together for another game.');root.classList.toggle('native-result',native);if(view?.phase==='complete')card.append(el('p',view.wins.join(' — '),'result-score'));const rank=ratingSummary(event);if(rank)card.append(el('p',rank,'rank-line'));card.append(button(event.ranked?'Find another match':'Return to character select',()=>onReturnLobby(event),'primary'),button('Back to online menu',()=>onBack(selected),'quiet'));}
 function notice(message){const p=el('p',message,'competitive-notice');p.setAttribute('role','status');root.querySelector('.competitive-card')?.prepend(p);}
 function hide(){root.hidden=true;document.body.classList.remove('competitive-open');}
 // Reserve both fallback corners until the host's measured insets are ready.
 function layout(){const l=window.YouGame?.ui?.getLayout?.(document.getElementById('play-surface'));const i=l?.insets||{};root.style.setProperty('--comp-top',`${Math.max(80,Number(i.top)||0)}px`);root.style.setProperty('--comp-bottom',`${Math.max(76,Number(i.bottom)||0)}px`);root.style.setProperty('--comp-left',`${Math.max(20,Number(i.left)||0)}px`);root.style.setProperty('--comp-right',`${Math.max(20,Number(i.right)||0)}px`);}
 window.YouGame?.ui?.onChange?.(layout);window.addEventListener('resize',layout);layout();
 const focusMove=direction=>{const buttons=[...root.querySelectorAll('button:not(:disabled)')];if(!buttons.length)return;const focused=document.activeElement;const at=buttons.indexOf(focused);buttons[at<0?(direction>0?0:buttons.length-1):(at+direction+buttons.length)%buttons.length].focus();};
 root.addEventListener('keydown',e=>{if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp'].includes(e.code)){e.preventDefault();focusMove(['ArrowLeft','ArrowUp'].includes(e.code)?-1:1);}});
 let held=false;
 function controller(){if(!root.hidden){const adapterInput=readController();const pad=adapterInput===null?[...(navigator.getGamepads?.()||[])].find(p=>p?.connected):null;const direction=adapterInput?.direction??(pad&&(pad.buttons[13]?.pressed||pad.buttons[15]?.pressed||pad.axes[0]>.55||pad.axes[1]>.55)?1:pad&&(pad.buttons[12]?.pressed||pad.buttons[14]?.pressed||pad.axes[0]<-.55||pad.axes[1]<-.55)?-1:0);const select=adapterInput?.select??pad?.buttons[0]?.pressed;const back=adapterInput?.back??pad?.buttons[1]?.pressed;if(!held){if(direction)focusMove(direction);else if(select){if(root.contains(document.activeElement)&&document.activeElement.matches('button:not(:disabled)'))document.activeElement.click();else focusMove(1);}else if(back&&!lastView)onBack(selected);}held=!!(direction||select||back);}else held=false;requestAnimationFrame(controller);}requestAnimationFrame(controller);
 return {setup,lobby,show,result,hide,notice,get visible(){return !root.hidden;},get view(){return lastView;}};
}
